# https://developers.openai.com/codex/config-reference
model = "gpt-5.4"
model_reasoning_effort = "high"
# file_opener = "zed"
personality = "pragmatic"
suppress_unstable_features_warning = true

[features]
apps = false
collaboration_modes = true
multi_agent = true
personality = true
runtime_metrics = true
shell_tool = true
unified_exec = true
steer = true

[projects."/Users/phatblat"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[tui.model_availability_nux]
"gpt-5.3-codex-spark" = 3
