#
# .prettierrc.toml
# Global Prettier configuration file
# https://prettier.io/docs/en/configuration.html
# https://toml.io/en/
#

# .prettierrc.toml
trailingComma = "es5"
tabWidth = 2
semi = false
singleQuote = true
