tap "cloudfoundry/tap"
tap "github/gh"
tap "heroku/brew"
tap "holgerbrandl/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-eid"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "kylef/formulae"
tap "mas-cli/tap"
tap "peripheryapp/periphery"
tap "phatblat/services"
tap "thoughtbot/formulae"
tap "vapor/tap"
tap "vitorgalvao/tiny-scripts"
brew "antigen"
brew "artifactory"
brew "openssl@1.1"
brew "sqlite"
brew "asciinema"
brew "clingo"
brew "augeas"
brew "autoconf"
brew "automake"
brew "node"
brew "babel"
brew "bash"
brew "bat"
brew "boost"
brew "burl"
brew "ocaml"
brew "ocamlbuild"
brew "dialog"
brew "certbot"
brew "cloc"
brew "cmake"
brew "cmatrix"
brew "configen"
brew "coreutils"
brew "cowsay"
brew "cscope"
brew "ctags"
brew "curl"
brew "diff-so-fancy"
brew "direnv"
brew "doxygen"
brew "duti"
brew "f3"
brew "fileicon"
brew "findutils"
brew "firebase-cli"
brew "pcre2"
brew "fish"
brew "fortune"
brew "libpng"
brew "freetype"
brew "gcovr"
brew "gettext"
brew "libtiff"
brew "git"
brew "git-filter-repo"
brew "git-lfs"
brew "glib"
brew "gmp"
brew "gnu-sed"
brew "libevent"
brew "libidn2"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "libgpg-error"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "gnupg"
brew "go"
brew "go-jira"
brew "libmaxminddb"
brew "tokyo-cabinet"
brew "goaccess"
brew "gox"
brew "gradle"
brew "groovy"
brew "helm"
brew "highlight"
brew "hub"
brew "ilmbase"
brew "python"
brew "shared-mime-info"
brew "libtool"
brew "openjpeg"
brew "webp"
brew "imagemagick"
brew "jabba"
brew "jansson"
brew "jenv"
brew "jfrog-cli-go"
brew "oniguruma"
brew "jq"
brew "jsonlint"
brew "jsonpp"
brew "kotlin"
brew "krb5"
brew "kubernetes-cli"
brew "less"
brew "libewf"
brew "libmagic"
brew "libressl"
brew "libssh"
brew "libssh2"
brew "libyaml"
brew "ruby"
brew "macvim", link: false
brew "make"
brew "makedepend"
brew "mas"
brew "maven"
brew "mint"
brew "mtr"
brew "ncurses"
brew "nginx"
brew "ninja"
brew "nvm"
brew "opam"
brew "packer"
brew "pacvim"
brew "perl"
brew "pixman"
brew "pkg-config"
brew "postgresql"
brew "qemu"
brew "radare2"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "rename"
brew "rlwrap"
brew "screenresolution"
brew "shellcheck"
brew "sl"
brew "socat"
brew "sonar-scanner"
brew "sourcekitten"
brew "speedtest-cli"
brew "sphinx-doc"
brew "swiftplate"
brew "tailor"
brew "task"
brew "tasksh"
brew "telnet"
brew "terminal-notifier"
brew "thefuck"
brew "tig"
brew "utf8proc"
brew "tmux"
brew "trash"
brew "travis"
brew "tree"
brew "uncrustify"
brew "utimer"
brew "wget"
brew "xcproj"
brew "xctool"
brew "yara"
brew "yarn"
brew "zsh"
brew "cloudfoundry/tap/cf-cli"
brew "github/gh/gh"
brew "heroku/brew/heroku-node"
brew "heroku/brew/heroku"
brew "holgerbrandl/tap/kscript"
brew "kylef/formulae/swiftenv"
brew "phatblat/services/pbjenkins"
brew "thoughtbot/formulae/liftoff"
brew "vitorgalvao/tiny-scripts/cask-repair"
mas "1Password 7", id: 1333542190
mas "Airmail", id: 918858936
mas "Bear", id: 1091189122
mas "Clean", id: 418412301
mas "Cleaner for Xcode", id: 1296084683
mas "Cosmicast", id: 1435195637
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "Deliveries", id: 924726344
mas "Disk Care", id: 913724705
mas "Display Menu", id: 549083868
mas "Divvy", id: 413857545
mas "Dumper", id: 781577745
mas "Fantastical", id: 975937182
mas "Houseparty", id: 1381523962
mas "Install macOS High Sierra", id: 1246284741
mas "iStat Mini", id: 927292435
mas "Jira", id: 1475897096
mas "Key Codes", id: 414568915
mas "Later", id: 1125131804
mas "Leech", id: 1101735327
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Memory Diag", id: 748212890
mas "Moom", id: 419330170
mas "Quests Alpha", id: 1447415753
mas "ReadKit", id: 588726889
mas "Server", id: 883878097
mas "Slack", id: 803453959
mas "Spillo", id: 873245660
mas "SSDReporter", id: 980258689
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
mas "WebP Viewer", id: 1323414118
mas "xScope", id: 889428659
