# Manage TextMate bundles.
function tmbundles
    set -l bundles blackpearl editorconfig fish gradle tomorrow-theme ublime

    set -l bundle_dev ~/dev/textmate
    set -l bundle_dir ~/Library/Application\ Support/TextMate/Bundles

    if not test -e $bundle_dev
        mkdir -p $bundle_dev
    end
    if not test -e $bundle_dir
        mkdir -p $bundle_dir
    end

    pushd $bundle_dev

    for bundle in $bundles
        if not test -e $bundle.tmbundle
            switch $bundle
                case blackpearl
                    clone_or_pull $bundle.tmbundle/Themes git@github.com:ajwitte/textmate-goodies.git

                    tmbundleplist \
                        "Black Pearl Theme" \
                        "Colorful and Black &amp; White color schemes. Plist generated by tmbundles function." \
                        git@github.com:ajwitte/textmate-goodies.git \
                    >$bundle.tmbundle/Info.plist

                case editorconfig
                    clone_or_pull editorconfig it@github.com:Mr0grog/editorconfig-textmate.git

                    set -l version 0.3.1
                    # curl -L -O -#
                    curl --location --remote-name --progress-bar \
                        https://github.com/Mr0grog/editorconfig-textmate/releases/download/v$version/editorconfig-textmate-$version.tmplugin.zip

                    set newest_file (ls -1t | head -n 1)
                    unzip -o $newest_file
                        and rm -f $newest_file

                    open editorconfig-textmate.tmplugin

                    # Create a dummy bundle file so install isn't repeated.
                    touch $bundle.tmbundle

                case fish
                    clone_or_pull $bundle.tmbundle git@github.com:l15n/fish-tmbundle.git

                case gradle
                    clone_or_pull $bundle.tmbundle git@github.com:alkemist/gradle.tmbundle.git

                case tomorrow-theme
                    clone_or_pull $bundle git@github.com:chriskempson/tomorrow-theme.git
                    set bundle "tomorrow-theme/textmate2/Tomorrow Theme"

                case ublime
                    clone_or_pull $bundle.tmbundle/Themes git@github.com:imagentleman/ublime.git

                    # Add a minimal bundle plist
                    set -l uuid (uuidgen)
                    echo \
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
	<key>name</key>
	<string>Ublime Color Schemes</string>
	<key>description</key>
	<string>Colorful and Black &amp; White color schemes. Plist generated by tmbundles function.</string>
	<key>uuid</key>
	<string>$uuid</string>
	<key>source</key>
	<dict>
		<key>method</key>
		<string>git</string>
		<key>url</key>
		<string>git@github.com:imagentleman/ublime.git</string>
	</dict>
</dict>
</plist>
"\
                    >$bundle.tmbundle/Info.plist
            end
        end
        open $bundle.tmbundle
    end

    echo $bundle_dev
    ls
    popd
end
