# Sequencing
# - After: cask (textmate)
function 📝_textmate \
    --description='Manage TextMate bundles.'

    echo "📝 TextMate - https://github.com/textmate/textmate"
    echo

    set -l bundles blackpearl dashmate editorconfig fish gradle kotlin tomorrow-theme ublime

    set -l bundle_dev ~/dev/textmate
    set -l bundle_dir ~/Library/Application\ Support/TextMate/Bundles

    # Create parent directories
    createdirs $bundle_dev $bundle_dir

    pushd $bundle_dev

    for bundle in $bundles
        if not test -e $bundle.tmbundle
            switch $bundle
                case blackpearl
                    clone_or_pull $bundle.tmbundle/Themes git@github.com:ajwitte/textmate-goodies.git

                    tmbundleplist \
                        "Black Pearl Theme" \
                        "Colorful and Black &amp; White color schemes. Plist generated by tmbundleplist function." \
                        git@github.com:ajwitte/textmate-goodies.git >$bundle.tmbundle/Info.plist

                    # https://github.com/ram-nadella/DashMate.tmbundle#readme
                case dashmate
                    clone_or_pull DashMate.tmbundle git@github.com:ram-nadella/DashMate.tmbundle.git

                    # https://github.com/Mr0grog/editorconfig-textmate
                case editorconfig
                    clone_or_pull $bundle git@github.com:Mr0grog/editorconfig-textmate.git

                    set -l ec_version 0.3.1
                    # curl -L -O -#
                    curl --location --remote-name --progress-bar \
                        https://github.com/Mr0grog/editorconfig-textmate/releases/download/v$ec_version/editorconfig-textmate-$ec_version.tmplugin.zip

                    set newest_file (ls -1t | head -n 1)
                    unzip -o $newest_file
                    and rm -f $newest_file

                    status is-login
                    and open editorconfig-textmate.tmplugin

                    # Create a dummy bundle file so install isn't repeated.
                    touch $bundle.tmbundle

                    # https://github.com/l15n/fish-tmbundle
                case fish
                    clone_or_pull $bundle.tmbundle git@github.com:l15n/fish-tmbundle.git

                    # https://github.com/alkemist/gradle.tmbundle
                case gradle
                    clone_or_pull $bundle.tmbundle git@github.com:alkemist/gradle.tmbundle.git

                case kotlin
                    clone_or_pull $bundle git@github.com:sargunster/kotlin-textmate-bundle.git
                    set bundle "$bundle/Kotlin"

                    # https://github.com/chriskempson/tomorrow-theme
                case tomorrow-theme
                    clone_or_pull $bundle git@github.com:chriskempson/tomorrow-theme.git
                    set bundle "tomorrow-theme/textmate2/Tomorrow Theme"

                    # https://github.com/imagentleman/ublime
                case ublime
                    clone_or_pull $bundle.tmbundle/Themes git@github.com:imagentleman/ublime.git

                    tmbundleplist \
                        "Ublime Color Schemes" \
                        "Colorful and Black &amp; White color schemes. Plist generated by tmbundleplist function." \
                        git@github.com:imagentleman/ublime.git >$bundle.tmbundle/Info.plist
            end
        end

        if test (filesize $bundle.tmbundle) -gt 0
            status is-login
            and open $bundle.tmbundle
        end
    end

    echo $bundle_dev
    ls
    popd
end
