#!/usr/bin/env bats
# omp-profiles.bats — profile config rendering and Subconscious pricing sync

load helpers/setup

setup() {
  command -v yq >/dev/null || skip "yq is not installed"
  root="$(mktemp -d)"
  mkdir -p "$root/scripts" "$root/.omp/agent" "$root/.omp/profiles/p/agent"
  cp "$HOME/scripts/generate-omp-profiles.sh" "$root/scripts/"
  cat >"$root/.omp/agent/config.yml" <<'EOF'
modelRoles:
  default: main/model
  vision: main/vision
cycleOrder: [a, b, c]
tools:
  approvalMode: yolo
  approval:
    bash: ask
    read: allow
setupVersion: 2
EOF
  cat >"$root/.omp/profiles/p/agent/overrides.yml" <<'EOF'
modelRoles:
  default: p/model
cycleOrder: [x]
tools:
  approval:
    bash: allow
EOF
  render="$root/scripts/generate-omp-profiles.sh"
  rendered="$root/.omp/profiles/p/agent/config.yml"
}

teardown() {
  rm -rf "$root"
}

@test "generate-omp-profiles: main's modelRoles never carry over" {
  run "$render"
  [ "$status" -eq 0 ]
  [ "$(yq '.modelRoles | keys | join(",")' "$rendered")" = "default" ]
  [ "$(yq '.modelRoles.default' "$rendered")" = "p/model" ]
}

@test "generate-omp-profiles: maps merge and arrays and scalars replace" {
  run "$render"
  [ "$status" -eq 0 ]
  [ "$(yq '.tools.approval.bash' "$rendered")" = "allow" ]
  [ "$(yq '.tools.approval.read' "$rendered")" = "allow" ]
  [ "$(yq '.tools.approvalMode' "$rendered")" = "yolo" ]
  [ "$(yq '.cycleOrder | join(",")' "$rendered")" = "x" ]
  [ "$(yq '.setupVersion' "$rendered")" = "2" ]
}

@test "generate-omp-profiles: rendered file says it is generated" {
  run "$render"
  [ "$status" -eq 0 ]
  [[ "$(head -1 "$rendered")" == "# Generated by"* ]]
}

@test "generate-omp-profiles --check passes right after a render" {
  "$render"
  run "$render" --check
  [ "$status" -eq 0 ]
}

@test "generate-omp-profiles --check fails when the main config changes" {
  "$render"
  yq -i '.setupVersion = 3' "$root/.omp/agent/config.yml"
  run "$render" --check
  [ "$status" -eq 1 ]
  [[ "$output" == *"stale: .omp/profiles/p/agent/config.yml"* ]]
}

@test "generate-omp-profiles --check fails when a profile config is edited in place" {
  "$render"
  yq -i '.setupVersion = 9' "$rendered"
  run "$render" --check
  [ "$status" -eq 1 ]
}

@test "generate-omp-profiles: committed profile configs are current" {
  run "$HOME/scripts/generate-omp-profiles.sh" --check
  [ "$status" -eq 0 ]
}

@test "sync-subconscious-models: parsing and rewriting unit tests pass" {
  run python3 "$HOME/tests/test_sync_subconscious_models.py"
  [ "$status" -eq 0 ]
}
