// Generated by scripts/agent-harnesses.py; do not edit directly.
// Copyright: Ben Chatelain. Apache 2.0.

import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

type GuardResult = { decision: "allow" | "warn" | "deny"; reason?: string };

function guard(args: string[]): GuardResult {
  const script = join(homedir(), "scripts", "agent-harnesses.py");
  try {
    const output = execFileSync("python3", [script, "guard", "--harness", "pi", ...args], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output) as GuardResult;
  } catch (error: any) {
    const output = error?.stdout?.toString?.() || "";
    if (output) return JSON.parse(output) as GuardResult;
    return { decision: "deny", reason: "Shared guard failed closed" };
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", (_event, ctx) => {
    ctx.ui.setStatus("harness", "shared harness");
  });

  pi.on("tool_call", async (event) => {
    let result: GuardResult = { decision: "allow" };
    if (event.toolName === "bash") {
      result = guard(["--tool", "bash", "--command", String(event.input.command || "")]);
    } else if (event.toolName === "write" || event.toolName === "edit") {
      const path = String(event.input.file_path || event.input.path || "");
      const content = String(event.input.content || event.input.new_string || "");
      result = guard(["--tool", event.toolName, "--path", path, "--content", content]);
    }
    if (result.decision === "deny") return { block: true, reason: result.reason || "Blocked by shared harness guard" };
    return undefined;
  });

  pi.registerCommand("harness-agents", {
    description: "List shared specialist agents",
    handler: async (_args, ctx) => {
      ctx.ui.notify("Shared specialist agents are registered in ~/.pi/agent/agents.json", "info");
    },
  });

  pi.registerTool({
    name: "harness_agent_registry",
    label: "Harness Agents",
    description: "Return the shared specialist agent registry.",
    parameters: Type.Object({}),
    async execute() {
      return {
        content: [{ type: "text", text: "Read ~/.pi/agent/agents.json for shared specialist agent definitions." }],
        details: { path: "~/.pi/agent/agents.json" },
      };
    },
  });
}
