substituters = https://cache.nixos.org https://ditto-ci.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ditto-ci.cachix.org-1:pVt0yAukYhUl6y5xh5B9Qs23+sn0FEl+zYs8e0fXJGQ=
netrc-file = /Users/phatblat/.config/nix/netrc
