//! Port of the generated-artifact deny path: `load_generated_manifest`,
//! `generated_relpath`, and `generated_path_warning`
//! (`scripts/agent-harnesses.py:728-786`).

use serde_json::Value;
use std::collections::BTreeMap;
use std::path::Path;

#[derive(Debug, Clone, Default)]
pub struct ManifestEntry {
    pub source: String,
}

/// Port of `load_generated_manifest` (agent-harnesses.py:728-739). Fails
/// open on purpose: a missing or malformed manifest must not wedge every
/// write in every harness. `just harness-check` is what catches the
/// manifest going stale.
pub fn load_generated_manifest(manifest_path: &Path) -> BTreeMap<String, ManifestEntry> {
    let Ok(text) = std::fs::read_to_string(manifest_path) else {
        return BTreeMap::new();
    };
    let Ok(Value::Object(map)) = serde_json::from_str::<Value>(&text) else {
        return BTreeMap::new();
    };
    map.into_iter()
        .map(|(key, value)| {
            let source = value
                .get("source")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            (key, ManifestEntry { source })
        })
        .collect()
}

/// Port of `generated_relpath` (agent-harnesses.py:742-763). Matches on the
/// tail of the path (like Python's `posix.endswith("/" + rel)`) so a
/// worktree copy of the repository, where the same artifact lives under a
/// different prefix, is still recognized as generated. Uses the same
/// filesystem-free lexical normalization as `policy::evaluate_write`, for
/// the identical reason: `Path.resolve()` on a path that does not exist yet
/// must not diverge from a path that does.
pub fn generated_relpath(path: &str, manifest_path: &Path) -> Option<String> {
    let manifest = load_generated_manifest(manifest_path);
    if manifest.is_empty() {
        return None;
    }
    let candidate = crate::paths::normalize_str(path);
    for key in manifest.keys() {
        let rel = key.strip_prefix("~/").unwrap_or(key.as_str());
        if candidate == rel || candidate.ends_with(&format!("/{rel}")) {
            return Some(key.clone());
        }
    }
    None
}

/// Port of `generated_path_warning` (agent-harnesses.py:766-786). The
/// returned string is byte-identical to the Python one, including the
/// trailing ", then regenerate." — the parity test asserts on this text.
pub fn generated_path_warning(tool: &str, path: &str, manifest_path: &Path) -> String {
    let normalized_tool = tool.to_lowercase();
    let normalized_tool = normalized_tool.trim();
    if !matches!(
        normalized_tool,
        "write" | "edit" | "multiedit" | "file_write" | "file_edit"
    ) {
        return String::new();
    }
    let Some(key) = generated_relpath(path, manifest_path) else {
        return String::new();
    };
    let manifest = load_generated_manifest(manifest_path);
    let source = manifest.get(&key).map(|e| e.source.as_str()).unwrap_or("");
    let target = if !source.is_empty() {
        format!("Edit {source} instead")
    } else {
        "Edit its source instead".to_string()
    };
    format!(
        "{key} is generated by scripts/agent-harnesses.py and will be overwritten by the next `just harness-generate`. {target}, then regenerate."
    )
}
