// Generated by scripts/agent-harnesses.py; do not edit directly.
// Copyright: Ben Chatelain. Apache 2.0.

import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Plugin } from "@opencode-ai/plugin";

type GuardResult = { decision: "allow" | "warn" | "deny"; reason?: string };

function guard(args: string[]): GuardResult {
  const script = join(homedir(), "scripts", "agent-harnesses.py");
  try {
    const output = execFileSync("python3", [script, "guard", "--harness", "opencode", ...args], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output) as GuardResult;
  } catch (error: any) {
    const output = error?.stdout?.toString?.() || "";
    if (output) return JSON.parse(output) as GuardResult;
    return { decision: "deny", reason: "Shared guard failed closed" };
  }
}

export const HarnessPlugin: Plugin = async () => ({
  async "experimental.chat.system.transform"(_input, output) {
    output.system.push("Use shared harness instructions from ~/.agents/harness/instructions.md.");
  },

  async "experimental.session.compacting"(_input, output) {
    output.context.push("Preserve modified files, current branch, pending tasks, test results, and harness parity gaps.");
  },

  async "tool.execute.before"(input, output) {
    const args = output.args || {};
    let result: GuardResult = { decision: "allow" };

    if (input.tool === "bash") {
      result = guard(["--tool", "bash", "--command", String(args.command || "")]);
    } else if (input.tool === "write" || input.tool === "edit") {
      const path = String(args.file_path || args.path || "");
      const content = String(args.content || args.new_string || "");
      result = guard(["--tool", input.tool, "--path", path, "--content", content]);
    }

    if (result.decision === "deny") {
      throw new Error(result.reason || "Blocked by shared harness guard");
    }
  },
});

export default HarnessPlugin;
