#!/usr/bin/env python3
"""Validate SKILL.md files with skills-ref, relaxed for known harness-specific
frontmatter fields that carry real meaning in this repo but aren't part of the
upstream Agent Skills spec (agentskills/agentskills).

skills-ref itself has no allowlist/config mechanism for extra fields (see
validator.ALLOWED_FIELDS, a hardcoded set) — this wrapper calls its library
functions directly and subtracts EXTRA_ALLOWED before checking, so every real
spec rule (name/dir match, casing, length caps, compatibility typing, etc.)
still applies in full.

Run with skills-ref's own interpreter (has strictyaml/click installed):
    ~/.local/pipx/venvs/skills-ref/bin/python3 .agents/scripts/skills-check.py <dir>...

Exit codes match `skills-ref validate`: 0 = all valid, 1 = any failures.
"""

import sys
from pathlib import Path

from skills_ref import errors, parser, validator

# Fields observed in this repo's SKILL.md frontmatter that are NOT in the
# upstream Agent Skills spec but ARE consumed by something real here:
#
#   version                  - per-skill semver; openclaw host pins a fixed
#                               value via extraFields, other templates declare
#                               their own (gstack/scripts/hosts/*.ts)
#   triggers                 - keyword list; allowlisted verbatim for the
#                               "gbrain" ingestion host (hosts/gbrain.ts
#                               keepFields includes 'triggers')
#   preamble-tier             - build-time only; selects preamble bash tier
#                               1-4, hard error if out of range
#                               (resolvers/preamble.ts)
#   hooks                     - documents/drives the Claude Code hook this
#                               skill installs at setup (careful/freeze/guard)
#   disable-model-invocation - host-native Claude Code / Factory field:
#                               blocks automatic model-initiated invocation
#   user-invocable            - host-native field: explicitly allowlisted for
#                               the Factory host (hosts/factory.ts keepFields)
#   argument-hint             - host-native Claude Code slash-command field
#   interactive                - documents that a skill runs in interactive
#                               Q&A mode (plan-*-review skills)
#   gbrain                    - build-time-only block (schema, context_queries)
#                               consumed by gstack/scripts/resolvers/gbrain.ts
#                               during `bun run gen:skill-docs` to splice
#                               literal bash into the generated skill body;
#                               inert by the time SKILL.md ships
#   author, date, source,
#   compiled-by               - provenance-only, used by the `boris` skill
#                               (compiled from an external blog post)
#
# .claude/skills/*/SKILL.md files are BUILD ARTIFACTS regenerated by
# `bun run gen:skill-docs` from .claude/skills/*/SKILL.md.tmpl sources; do
# not hand-edit them to satisfy this checker.
EXTRA_ALLOWED = {
    "version",
    "triggers",
    "preamble-tier",
    "hooks",
    "disable-model-invocation",
    "user-invocable",
    "argument-hint",
    "interactive",
    "gbrain",
    "author",
    "date",
    "source",
    "compiled-by",
}


def validate_relaxed(skill_dir: Path) -> list[str]:
    """Same contract as skills_ref.validator.validate(), minus EXTRA_ALLOWED."""
    if not skill_dir.exists():
        return [f"Path does not exist: {skill_dir}"]
    if not skill_dir.is_dir():
        return [f"Not a directory: {skill_dir}"]

    skill_md = parser.find_skill_md(skill_dir)
    if skill_md is None:
        return ["Missing required file: SKILL.md"]

    try:
        metadata, _ = parser.parse_frontmatter(skill_md.read_text())
    except errors.ParseError as e:
        return [str(e)]

    metadata = {k: v for k, v in metadata.items() if k not in EXTRA_ALLOWED}
    return validator.validate_metadata(metadata, skill_dir)


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: skills-check.py <skill-dir> [...]", file=sys.stderr)
        return 2

    failed = 0
    for arg in sys.argv[1:]:
        skill_dir = Path(arg)
        errors = validate_relaxed(skill_dir)
        if errors:
            failed += 1
            print(f"Validation failed for {skill_dir}:", file=sys.stderr)
            for error in errors:
                print(f"  - {error}", file=sys.stderr)
        else:
            print(f"Valid skill: {skill_dir}")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
