#!/usr/bin/env bash
# Generated by scripts/agent-harnesses.py; do not edit directly.
# crush PreToolUse adapter for the compiled harness guard (crates/ness,
# installed by `just ness-install`). Fails closed when it is missing.
#
# Copyright: Ben Chatelain. Apache 2.0.

set -euo pipefail

deny() {
    printf '%s
' "$1" >&2
    exit 2
}
trap 'deny "shared guard failed closed: hook error"' ERR

ness="$HOME/.local/bin/ness"
[ -x "$ness" ] || deny "shared guard failed closed: $ness is not installed (run: just ness-install)"
exec "$ness" hook --harness crush
