#
# ~/.cargo/cargo.toml
# https://doc.rust-lang.org/cargo/reference/config.html
#

[build]
# https://github.com/mozilla/sccache#usage
rustc-wrapper = "/opt/homebrew/bin/sccache"

[profile.dev]
# https://endler.dev/2020/rust-compile-times/#xfaster-incremental-debug-builds-on-macos
split-debuginfo = "unpacked"
