#!/usr/bin/env zsh

# apv - Quick nav to ApplePlatformVersions dir
local apv_dir="$HOME/dev/ApplePlatformVersions"

if [[ ! -d "$apv_dir" ]]; then
cd ~/dev || return
git clone git@github.com:phatblat/ApplePlatformVersions.git
else
cd "$apv_dir" || return
git pull
fi

lg10
