#!/usr/bin/env zsh

# col1 - Prints the first column of input (first argument)
# Multi-line content can be passed on stdin, assumed when given no arguments, or
# a single dash.
if [[ $# -eq 0 || "$1" == "-" ]]; then
    awk '{print $1}'
else
    echo "$1" | awk '{print $1}'
fi
