#!/usr/bin/env zsh

# derived_data - Spins up a RAM disk for Xcode DerivedData
local quiet="$1"
local drive_name="DerivedData"
local default_size=10
local target_path="/Volumes/$drive_name"
local icon_file="$HOME/Pictures/Icons/Agua Onyx Icons/Onyx Media Drive.png"

if [[ -d "$target_path" ]]; then
echo "$drive_name already mounted"
local output
output=$(diskutil list "$drive_name")
else
local output
output=$(ramdisk "$default_size" "$drive_name")
fileicon set "$target_path" "$icon_file"
fi

if [[ -z "$quiet" ]]; then
echo "$output"
fi
