#!/usr/bin/env zsh

# din - Remove all docker images
echo "Running command to: Remove all Docker images"

# Prune unused images
dip

local images
images=$(docker image ls --format '{{.ID}}')
if [[ -n "$images" ]]; then
  docker image rm $images
else
  echo "***No images present to remove***"
fi
