#!/usr/bin/env zsh

# dra - Remove all stopped docker containers
echo "Running command to: Remove all stopped containers"
local running_containers
running_containers=$(docker container ls --all --quiet)
if [[ -n "$running_containers" ]]; then
    docker container rm "$running_containers"
else
    echo "No containers found to remove"
fi
