#!/usr/bin/env zsh


# fileowner - Displays the owner of a file
function fileowner() {
    local file="$1"
    if [[ -z "$file" ]]; then
        echo "Usage: fileowner file"
        return 1
    fi

    if [[ "$OSTYPE" == "darwin"* ]]; then
        ls -ld "$file" | awk '{print $3}'
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        stat --format=%U "$file"
    fi
}
