#!/usr/bin/env zsh

# gem_install - Install a Ruby gem at the system level (requires sudo permissions)
local gem_name="$1"

if [[ -z "$gem_name" ]]; then
    echo "Usage: gem_install gem_name ..."
    return 1
fi

shift
gem install --force "$gem_name" --bindir "$(brew --prefix)/bin" "$@"
