#!/usr/bin/env zsh

# git-plist-filter - Converts plist data to XML format (stdin->stdout)
# had to do this because git doesn't like attaching stdin and out to plutil (waitpid error)

# TMPDIR isn't set for ssh logins!
local TMPDIR="${TMPDIR:-$(getconf DARWIN_USER_TEMP_DIR)}"
local function_name="git-plist-filter"

local TMPFILE
TMPFILE=$(mktemp "$TMPDIR/$function_name.XXXXXX")

# Drop stdin to temp file
cat > "$TMPFILE"
plutil -convert xml1 "$TMPFILE"
cat "$TMPFILE"
rm "$TMPFILE"
