#!/usr/bin/env zsh


# gpgcopypub - Copies the public key for any GPG key found
function gpgcopypub() {
    local keyid=$(gpgkeyid)
    local gpg_key_ascii=$(gpg --armor --export "$keyid")
    echo "$gpg_key_ascii" | pbcopy
    echo "GPG key copied to pasteboard (keyid: $keyid)"
}
