#!/usr/bin/env zsh


# gpgkeyid - Prints the long format key identifiers of all GPG keys found
function gpgkeyid() {
    gpg --list-secret-keys \
            --keyid-format short \
        | egrep -o "^sec.*/\w+" \
        | cut -d "/" -f 2
}
