#!/usr/bin/env zsh

# gradle_debug - Toggles Gradle remote debugging on/off
# Usage: gradle_debug [on|off]
local heap_space="${GRADLE_HEAP_SPACE:--Xmx1g}"

if [[ -z "$GRADLE_OPTS" || $1 == "on" ]]; then
    export GRADLE_OPTS="${heap_space} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
    echo "Gradle debugging on"
    echo "GRADLE_OPTS: ${GRADLE_OPTS}"
else
    export GRADLE_OPTS="$heap_space"
    echo "Gradle debugging off"
fi
