#!/usr/bin/env zsh

# gv - Prints gradle version
function gv() {
    local output
    output=$(gradle --version)
    local gradle_version
    gradle_version=$(echo "$output" | sed -n '3p' | awk '{print $2}')
    echo "$gradle_version"
}
