#!/usr/bin/env zsh

function ignore() {
    local gitignore
    gitignore="$(root)/.gitignore"
    local ignore_list
    local commit_message

    touch "$gitignore"

    if [[ -s "$gitignore" ]]; then
        ignore_list=$(cat "$gitignore")
    else
        ignore_list=$(ignores)
        commit_message="chore: add standard ignores"
        echo "Creating .gitignore"
    fi

    if [[ $# -gt 0 ]]; then
        {
            printf '%s\n' "$@"
            printf '%s\n' "$ignore_list"
        } | sort -u > "$gitignore"
        commit_message="chore: ignore $*"
    else
        printf '%s\n' "$ignore_list" | sort -u > "$gitignore"
    fi

    if [[ -z "$commit_message" ]]; then
        echo "Nothing new added to ignores, just sorted and removed duplicates."
        return
    fi

    git add "$gitignore"
    git commit -m "$commit_message"
}
