#!/usr/bin/env zsh

# index - Prints the index of a value in a list
local value="$1"

if [[ -z "$value" ]]; then
  echo "Usage: index value \$list"
  return 1
fi

shift
local i=1
for item in "$@"; do
  if [[ "$item" == "$value" ]]; then
    echo $i
    return 0
  fi
  (( i++ ))
done

return 1
