#!/usr/bin/env zsh

# lga - Pretty history graph showing all
function lga() {
    git log \
        --all \
        --graph \
        --abbrev-commit \
        --date=relative \
        --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' \
        "$@"
}
