#!/usr/bin/env zsh

# lgg - Pretty history graph
git log \
--graph \
--abbrev-commit \
--date=relative \
--pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' \
"$@"
