#!/usr/bin/env zsh

# mdk - Quick nav to MDK
local platform="$1"
local path="$HOME/dev/mdk"

if [[ -n "$platform" ]]; then
case "$platform" in
i | ios)
path="$path/ios"
;;
a | android)
path="$path/android"
;;
esac
fi

pushd "$path" || return
