#!/usr/bin/env zsh

# members - List members of the given group
function members() {
    local group="$1"
    if [[ -z "$group" ]]; then
        echo "Usage: members group"
        return 1
    fi

    for user in $(dscl . -list /Users); do
        if dsmemberutil checkmembership -U "$user" -G "$group" | grep -q "is a member"; then
            echo "$user"
        fi
    done
}
