#!/usr/bin/env zsh

# mpv - Quick nav to MicrosoftPlatformVersions dir
local mpv_dir=~/dev/MicrosoftPlatformVersions

if [[ ! -d "$mpv_dir" ]]; then
cd ~/dev || return
git clone git@github.com:phatblat/MicrosoftPlatformVersions.git
else
cd "$mpv_dir" || return
git pull
fi

lg10
