#!/usr/bin/env zsh

# realmos - Manage Realm Object Server
function realmos() {
    local command="$1"
    echo "Realm Object Server"

    if [[ ! -e "$REALM_OBJECT_SERVER_PATH" ]]; then
        echo "No such path: $REALM_OBJECT_SERVER_PATH"
        return 1
    fi

    case "$command" in
    start)
        echo "Starting ROS at $REALM_OBJECT_SERVER_PATH"
        eval "$REALM_OBJECT_SERVER_PATH/start-object-server.command"
        ;;
    *)
        echo "Usage: realmos [start]"
        ;;
    esac
}
