#!/usr/bin/env zsh

# repo_new - Creates a new GitHub repo using the local dir as the root
local repo_name="$1"

if [[ -z "$repo_name" ]]; then
    echo 'Usage: repo_new [repo_name]'
    return 1
fi

gh repo create "$repo_name" --public --source=.
pborigin
pp
