#!/usr/bin/env zsh

# showgit_remote - Searches for .git repos recursively below the current dir, printing remote URL
showgit | while read -r git_dir; do
    local dir
    dir=$(dirname "$git_dir")
    echo "$dir"
    pushd "$dir" > /dev/null || return
    grep url .git/config
    popd > /dev/null || return
done
