#!/usr/bin/env zsh


# spotlight_reload - Reloads Spotlight which triggers a re-index
function spotlight_reload() {
    spotlight_disable

    sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
    sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist

    spotlight_enable
}
