#!/usr/bin/env zsh

# sshkey - Find the public key file
if [[ -f ~/.ssh/id_ed25519.pub ]]; then
    echo ~/.ssh/id_ed25519.pub
elif [[ -f ~/.ssh/id_rsa.pub ]]; then
    echo ~/.ssh/id_rsa.pub
else
    echo "Error: No SSH key file found." >&2
    return 1
fi
