#!/usr/bin/env zsh

# title - Sets window/tab title
local name="$1"

if [[ -z "$name" ]]; then
  echo "Usage: title Tab Name"
  return 1
fi

if [[ "$name" == "-" ]]; then
  unset TAB_TITLE
else
  export TAB_TITLE="$*"
fi
