#!/usr/bin/env zsh

# xcswitch - Switch the active version of Xcode
local xcode_version=$1

if ! user_is_admin; then
    echo "You must be an admin to run this command."
    return 1
fi

if [[ -z "$xcode_version" ]]; then
    echo "Usage: xcswitch <xcode_version>"
    echo "Version format: 8.3.2"
    return 1
fi

local xcode_path=/Applications/Xcode-$xcode_version.app
if [[ ! -e "$xcode_path" ]]; then
    echo "$xcode_path does not exist."
    return 2
fi

echo "Activating Xcode Version: $xcode_version"

# Switch the version of Xcode on the system.
xcss "$xcode_path"

# Create an Xcode.app symlink so tools that assume Xcode was installed via the
# MAS use the correct version.
pushd /Applications || return

# -h    If the link_name or link_dirname is a symbolic link, do not follow it.
# -f    If the proposed link already exists, unlink it so the link may occur.
# -s    Create a symbolic link.
# -v    Verbose, showing files as they are processed.
ln -hfsv "$(basename "$xcode_path")" Xcode.app

popd || return

xclist
echo "Activated $(xcsp | head -1)"
