#!/usr/local/bin/zsh
#-------------------------------------------------------------------------------
#
# cron/antigen_update
#
#-------------------------------------------------------------------------------

source $HOME/.dotfiles/cron/cron.env

antigen_dir="$HOME/dev/shell/antigen"
source "$antigen_dir/antigen.zsh"

antigen selfupdate
antigen update
