#!/usr/local/bin/zsh
#-------------------------------------------------------------------------------
#
# cron/antigen_update
#
#-------------------------------------------------------------------------------

source $HOME/.dotfiles/cron/cron.env

antigen_dir="$(brew --prefix)/Cellar/antigen/1/share"
source "$antigen_dir/antigen.zsh"

antigen selfupdate
antigen update
