#!/usr/bin/env python3
"""Inventory, generate, validate, and audit shared agent harness parity.

Copyright: Ben Chatelain. Apache 2.0.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tomllib
from typing import Any


sys.dont_write_bytecode = True

HOME = Path(os.environ.get("HOME", str(Path.home()))).resolve()
ROOT = HOME
SHARED = ROOT / ".agents" / "harness"
COMMAND_SOURCE = ROOT / ".claude" / "commands"
AGENT_SOURCE = ROOT / ".codex" / "agents"
SKILL_SOURCE = ROOT / ".agents" / "skills"
OPEN_CODE = ROOT / ".config" / "opencode"
PI_AGENT = ROOT / ".pi" / "agent"
VERIFIED_DATE = "2026-06-27"
MANAGED_HEADER = (
    "<!-- Generated by scripts/agent-harnesses.py; do not edit directly. -->"
)

sys.path.insert(0, str(SHARED / "hooks"))
try:
    from safety import evaluate  # type: ignore
except ImportError as exc:  # pragma: no cover - only hit before installation
    evaluate = None  # type: ignore
    SAFETY_IMPORT_ERROR = exc
else:
    SAFETY_IMPORT_ERROR = None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="action", required=True)

    inventory_parser = subparsers.add_parser(
        "inventory", help="Print discovered harness inventory"
    )
    inventory_parser.add_argument("--json", action="store_true", help="Emit JSON")

    generate_parser = subparsers.add_parser(
        "generate", help="Generate shared/native harness artifacts"
    )
    generate_parser.add_argument(
        "--check", action="store_true", help="Fail if generated artifacts are stale"
    )

    subparsers.add_parser(
        "validate", help="Validate manifest, generated artifacts, and local discovery"
    )

    audit_parser = subparsers.add_parser("audit", help="Print version and parity audit")
    audit_parser.add_argument("--json", action="store_true", help="Emit JSON")

    guard_parser = subparsers.add_parser(
        "guard", help="Evaluate a normalized tool call"
    )
    guard_parser.add_argument(
        "--harness", choices=["claude", "codex", "opencode", "pi"], required=True
    )
    guard_parser.add_argument("--tool", required=True)
    guard_parser.add_argument("--command", dest="shell_command", default="")
    guard_parser.add_argument("--path", default="")
    guard_parser.add_argument("--content", default="")
    guard_parser.add_argument("--cwd", default=str(ROOT))

    args = parser.parse_args()
    if args.action == "inventory":
        return command_inventory(json_output=args.json)
    if args.action == "generate":
        return command_generate(check=args.check)
    if args.action == "validate":
        return command_validate()
    if args.action == "audit":
        return command_audit(json_output=args.json)
    if args.action == "guard":
        return command_guard(args)
    raise AssertionError(args.action)


def command_inventory(*, json_output: bool) -> int:
    inventory = build_inventory()
    if json_output:
        print(json.dumps(inventory, indent=2, sort_keys=True))
    else:
        print(f"commands: {len(inventory['commands'])}")
        print(f"agents: {len(inventory['agents'])}")
        print(f"skills: {inventory['skills']['count']}")
        print("capabilities: " + ", ".join(inventory["capabilities"]))
    return 0


def command_generate(*, check: bool) -> int:
    expected = render_all()
    stale: list[Path] = []

    for path, content in expected.items():
        if path.exists() and path.read_text() == content:
            continue
        stale.append(path)

    if check:
        if stale:
            for path in stale:
                print(f"stale: {display_path(path)}", file=sys.stderr)
            return 1
        return 0

    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


def command_validate() -> int:
    errors: list[str] = []
    inventory = build_inventory()
    if len(inventory["commands"]) != 22:
        errors.append(
            f"expected 22 active commands, found {len(inventory['commands'])}"
        )
    if len(inventory["agents"]) != 6:
        errors.append(f"expected 6 specialist agents, found {len(inventory['agents'])}")
    if inventory["skills"]["count"] < 1:
        errors.append("expected shared skills in .agents/skills")
    if "code-review-graph" not in inventory["capabilities"]:
        errors.append("code-review-graph capability missing")

    if command_generate(check=True) != 0:
        errors.append("generated artifacts are stale")

    for config in (
        OPEN_CODE / "opencode.jsonc",
        PI_AGENT / "settings.json",
        ROOT / "docs" / "agent-harnesses.json",
    ):
        try:
            json.loads(config.read_text())
        except Exception as exc:  # noqa: BLE001 - report all parse failures
            errors.append(
                f"{display_path(config)} is not valid JSON/JSONC subset: {exc}"
            )

    if shutil.which("opencode"):
        result = subprocess.run(
            ["opencode", "debug", "config", "--pure"],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if result.returncode != 0:
            errors.append("opencode debug config --pure failed")

    if shutil.which("pi"):
        result = subprocess.run(
            ["pi", "list", "--no-approve"],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        if result.returncode != 0:
            errors.append("pi list --no-approve failed")

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("Agent harness parity checks passed")
    return 0


def command_audit(*, json_output: bool) -> int:
    manifest_path = ROOT / "docs" / "agent-harnesses.json"
    manifest = (
        json.loads(manifest_path.read_text())
        if manifest_path.exists()
        else build_manifest()
    )
    audit = {
        "verifiedDate": VERIFIED_DATE,
        "versions": {
            "claude": command_version(["claude", "--version"]),
            "codex": command_version(["codex", "--version"]),
            "opencode": command_version(["opencode", "--version"]),
            "pi": command_version(["pi", "--version"]),
        },
        "partial": [
            {
                "id": feature["id"],
                "harness": harness,
                "reason": state.get("gap_reason", ""),
                "next_action": state.get("next_action", ""),
            }
            for feature in manifest["features"]
            for harness, state in feature["harnesses"].items()
            if state["state"] in {"partial", "missing", "blocked"}
        ],
    }
    if json_output:
        print(json.dumps(audit, indent=2, sort_keys=True))
    else:
        print("# Agent Harness Audit")
        print()
        for harness, version in audit["versions"].items():
            print(f"- {harness}: {version or 'not installed'}")
        print()
        print("## Open Items")
        for item in audit["partial"]:
            print(f"- {item['id']} ({item['harness']}): {item['next_action']}")
    return 0


def command_guard(args: argparse.Namespace) -> int:
    if SAFETY_IMPORT_ERROR is not None:
        print(
            json.dumps(
                {
                    "decision": "deny",
                    "reason": f"safety module unavailable: {SAFETY_IMPORT_ERROR}",
                }
            )
        )
        return 2

    decision = evaluate(
        args.tool,
        command=args.shell_command,
        path=args.path,
        content=args.content,
        cwd=args.cwd,
    )
    payload = {
        "harness": args.harness,
        "tool": args.tool,
        "decision": decision.decision,
        "reason": decision.reason,
    }
    print(json.dumps(payload, sort_keys=True))
    return 0 if decision.allowed else 2


def build_inventory(*, include_prompts: bool = False) -> dict[str, Any]:
    commands = discover_commands()
    agents = discover_agents(include_prompts=include_prompts)
    skills = sorted(
        str(path.relative_to(SKILL_SOURCE).parent)
        for path in SKILL_SOURCE.glob("*/SKILL.md")
    )
    capabilities = ["shared-skills"]
    codex_config = ROOT / ".codex" / "config.toml"
    if codex_config.exists() and "code-review-graph" in codex_config.read_text():
        capabilities.append("code-review-graph")
    if (OPEN_CODE / "package.json").exists():
        capabilities.append("opencode-plugin")
    if shutil.which("pi"):
        capabilities.append("pi-extension")

    return {
        "commands": commands,
        "agents": agents,
        "skills": {"count": len(skills), "paths": skills},
        "capabilities": capabilities,
    }


def discover_commands() -> list[dict[str, Any]]:
    commands: list[dict[str, Any]] = []
    for path in sorted(COMMAND_SOURCE.rglob("*.md")):
        rel = path.relative_to(COMMAND_SOURCE)
        command_id = rel.with_suffix("").as_posix()
        body = path.read_text()
        frontmatter, _ = parse_frontmatter(body)
        commands.append(
            {
                "id": command_id,
                "native": command_id.replace("/", ":"),
                "description": frontmatter.get(
                    "description", first_nonempty_line(body)
                ),
                "argument_hint": frontmatter.get("argument-hint")
                or frontmatter.get("argument_hint", ""),
                "source": display_path(path),
                "shared": display_path(SHARED / "commands" / rel),
            }
        )
    return commands


def discover_agents(*, include_prompts: bool = False) -> list[dict[str, Any]]:
    agents: list[dict[str, Any]] = []
    for path in sorted(AGENT_SOURCE.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        name = data.get("name", path.stem)
        agent = {
            "id": name,
            "description": data.get("description", ""),
            "source": display_path(path),
            "shared": display_path(SHARED / "agents" / f"{name}.toml"),
        }
        if include_prompts:
            agent["prompt"] = data.get("developer_instructions", "")
        agents.append(agent)
    return agents


def render_all() -> dict[Path, str]:
    inventory = build_inventory(include_prompts=True)
    commands = inventory["commands"]
    agents = inventory["agents"]
    rendered: dict[Path, str] = {
        SHARED / "README.md": render_shared_readme(commands, agents),
        SHARED / "instructions.md": render_instructions(),
        SHARED / "hooks" / "contract.json": render_contract(),
        SHARED / "hooks" / "safety-policy.json": render_safety_policy(),
        ROOT / "docs" / "agent-harnesses.json": json.dumps(
            build_manifest(), indent=2, sort_keys=True
        )
        + "\n",
        ROOT / "docs" / "agent-harnesses.md": render_manifest_markdown(
            build_manifest()
        ),
        OPEN_CODE / "opencode.jsonc": render_opencode_config(commands, agents),
        OPEN_CODE / "plugins" / "harness.ts": render_opencode_plugin(),
        PI_AGENT / ".gitignore": render_pi_gitignore(),
        PI_AGENT / "settings.json": render_pi_settings(),
        PI_AGENT / "extensions" / "harness.ts": render_pi_extension(),
        PI_AGENT / "agents.json": json.dumps(
            {"agents": slim_agents(agents)}, indent=2, sort_keys=True
        )
        + "\n",
    }

    for command in commands:
        source = ROOT / command["source"].replace("~/", "")
        rel = Path(command["id"] + ".md")
        rendered[SHARED / "commands" / rel] = render_shared_command(source.read_text())
        rendered[OPEN_CODE / "commands" / f"{command['native']}.md"] = (
            render_native_command(command)
        )
        rendered[PI_AGENT / "prompts" / f"{command['native']}.md"] = render_pi_prompt(
            command
        )

    for agent in agents:
        source = ROOT / agent["source"].replace("~/", "")
        rendered[SHARED / "agents" / f"{agent['id']}.toml"] = render_shared_agent(
            source.read_text()
        )
        rendered[OPEN_CODE / "agents" / f"{agent['id']}.md"] = render_native_agent(
            agent
        )
        rendered[PI_AGENT / "agents" / f"{agent['id']}.md"] = render_pi_agent(agent)

    return rendered


def render_shared_readme(
    commands: list[dict[str, Any]], agents: list[dict[str, Any]]
) -> str:
    return f"""# Shared Agent Harness

{MANAGED_HEADER}

This directory is the portable harness layer for Claude, Codex, OpenCode, and Pi.
It keeps command prompts, specialist agent definitions, normalized hook contracts,
and shared safety policy in one place. Native harness directories should contain
thin generated adapters or tool-specific configuration only.

## Inventory

- Commands: {len(commands)}
- Specialist agents: {len(agents)}
- Shared skills source: `~/.agents/skills`
- Safety policy: `~/.agents/harness/hooks/safety.py`

"""


def render_instructions() -> str:
    return f"""# Shared Harness Instructions

{MANAGED_HEADER}

Always load repository instructions first, then use shared skills from
`~/.agents/skills` when a task matches a skill description. Prefer the canonical
command prompts under `~/.agents/harness/commands` and specialist agent
definitions under `~/.agents/harness/agents`.

Safety-sensitive lifecycle events must be normalized through
`~/.agents/harness/hooks/contract.json` and evaluated by the shared safety policy.
Adapters may add stricter native permissions, but they must not weaken a shared
deny decision.
"""


def render_contract() -> str:
    contract = {
        "version": 1,
        "events": {
            "session_start": {"fields": ["cwd", "session_id", "harness"]},
            "user_prompt": {"fields": ["prompt", "session_id", "harness"]},
            "tool_call": {
                "fields": [
                    "tool",
                    "command",
                    "path",
                    "content",
                    "session_id",
                    "harness",
                ]
            },
            "tool_result": {
                "fields": ["tool", "status", "output", "session_id", "harness"]
            },
            "compaction": {"fields": ["session_id", "reason", "harness"]},
            "failure": {"fields": ["tool", "error", "session_id", "harness"]},
        },
        "decisions": ["allow", "warn", "deny"],
    }
    return json.dumps(contract, indent=2, sort_keys=True) + "\n"


def render_safety_policy() -> str:
    policy = {
        "version": 1,
        "protected_paths": [
            ".env*",
            ".ssh/*",
            "*.pem",
            "*.key",
            ".aws/credentials",
            ".docker/config.json",
            ".claude/.credentials.json",
            ".codex/auth.json",
            ".pi/agent/auth.json",
        ],
        "blocked_command_categories": [
            "privilege-escalation",
            "destructive-filesystem",
            "device-writes",
            "pipe-to-shell",
            "obfuscated-execution",
        ],
        "secret_categories": [
            "ai-provider-key",
            "cloud-access-key",
            "vcs-token",
            "chat-token",
            "private-key",
            "password-assignment",
        ],
    }
    return json.dumps(policy, indent=2, sort_keys=True) + "\n"


def render_shared_command(source_text: str) -> str:
    return f"{MANAGED_HEADER}\n\n{source_text}"


def render_shared_agent(source_text: str) -> str:
    return f"# Generated by scripts/agent-harnesses.py; do not edit directly.\n{source_text}"


def render_native_command(command: dict[str, Any]) -> str:
    return f"""---
description: {json.dumps(command["description"])[1:-1]}
---

{MANAGED_HEADER}

Execute the shared `{command["id"]}` command prompt from:

`{command["shared"]}`

Pass user arguments through unchanged.
"""


def render_pi_prompt(command: dict[str, Any]) -> str:
    hint = (
        f'argument-hint: "{command["argument_hint"]}"\n'
        if command["argument_hint"]
        else ""
    )
    return f"""---
description: {json.dumps(command["description"])[1:-1]}
{hint}---

{MANAGED_HEADER}

Execute the shared `{command["id"]}` command prompt from:

`{command["shared"]}`

Arguments: $ARGUMENTS
"""


def render_native_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

Load the shared specialist definition from `{agent["shared"]}`.
"""


def render_pi_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

{agent["prompt"].strip()}
"""


def render_opencode_config(
    commands: list[dict[str, Any]], agents: list[dict[str, Any]]
) -> str:
    config = {
        "$schema": "https://opencode.ai/config.json",
        "instructions": ["~/.agents/harness/instructions.md"],
        "model": "anthropic/claude-sonnet-4-20250514",
        "small_model": "anthropic/claude-haiku-3-5-20241022",
        "share": "manual",
        "autoupdate": "notify",
        "permission": {
            "edit": "ask",
            "bash": {
                "git status*": "allow",
                "git diff*": "allow",
                "git log*": "allow",
                "git show*": "allow",
                "rg *": "allow",
                "find *": "allow",
                "ls *": "allow",
                "just harness-check": "allow",
                "rm *": "ask",
                "sudo *": "deny",
            },
            "external_directory": "ask",
            "webfetch": "ask",
        },
        "mcp": {
            "code-review-graph": {
                "type": "local",
                "command": [
                    "mise",
                    "exec",
                    "pipx:code-review-graph",
                    "--",
                    "code-review-graph",
                    "serve",
                ],
                "enabled": True,
                "timeout": 10000,
            }
        },
        "command": {
            command["native"]: {
                "description": command["description"],
                "template": f"Execute the shared harness command at {command['shared']} with arguments: $ARGUMENTS",
            }
            for command in commands
        },
        "agent": {
            agent["id"]: {
                "description": agent["description"],
                "mode": "subagent",
                "prompt": f"Load and follow the shared specialist agent definition at {agent['shared']} before acting.",
                "permission": {
                    "edit": "ask",
                    "bash": "ask",
                    "webfetch": "ask",
                    "external_directory": "ask",
                },
            }
            for agent in agents
        },
    }
    return json.dumps(config, indent=2, sort_keys=True) + "\n"


def render_opencode_plugin() -> str:
    return """// Generated by scripts/agent-harnesses.py; do not edit directly.
// Copyright: Ben Chatelain. Apache 2.0.

import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Plugin } from "@opencode-ai/plugin";

type GuardResult = { decision: "allow" | "warn" | "deny"; reason?: string };

function guard(args: string[]): GuardResult {
  const script = join(homedir(), "scripts", "agent-harnesses.py");
  try {
    const output = execFileSync("python3", [script, "guard", "--harness", "opencode", ...args], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output) as GuardResult;
  } catch (error: any) {
    const output = error?.stdout?.toString?.() || "";
    if (output) return JSON.parse(output) as GuardResult;
    return { decision: "deny", reason: "Shared guard failed closed" };
  }
}

export const HarnessPlugin: Plugin = async () => ({
  async "experimental.chat.system.transform"(_input, output) {
    output.system.push("Use shared harness instructions from ~/.agents/harness/instructions.md.");
  },

  async "experimental.session.compacting"(_input, output) {
    output.context.push("Preserve modified files, current branch, pending tasks, test results, and harness parity gaps.");
  },

  async "tool.execute.before"(input, output) {
    const args = output.args || {};
    let result: GuardResult = { decision: "allow" };

    if (input.tool === "bash") {
      result = guard(["--tool", "bash", "--command", String(args.command || "")]);
    } else if (input.tool === "write" || input.tool === "edit") {
      const path = String(args.file_path || args.path || "");
      const content = String(args.content || args.new_string || "");
      result = guard(["--tool", input.tool, "--path", path, "--content", content]);
    }

    if (result.decision === "deny") {
      throw new Error(result.reason || "Blocked by shared harness guard");
    }
  },
});

export default HarnessPlugin;
"""


def render_pi_settings() -> str:
    existing: dict[str, Any] = {}
    settings_path = PI_AGENT / "settings.json"
    if settings_path.exists():
        existing = json.loads(settings_path.read_text())

    merged = {
        **existing,
        "defaultProvider": existing.get("defaultProvider", "anthropic"),
        "defaultModel": existing.get("defaultModel", "claude-opus-4-8"),
        "defaultThinkingLevel": existing.get("defaultThinkingLevel", "medium"),
        "defaultProjectTrust": existing.get("defaultProjectTrust", "ask"),
        "enableSkillCommands": True,
        "skills": ["~/.agents/skills"],
        "prompts": ["~/.pi/agent/prompts"],
        "extensions": ["~/.pi/agent/extensions/harness.ts"],
        "compaction": {
            "enabled": True,
            "reserveTokens": 16384,
            "keepRecentTokens": 20000,
        },
        "retry": {
            "enabled": True,
            "maxRetries": 3,
            "baseDelayMs": 2000,
            "provider": {"maxRetries": 0, "maxRetryDelayMs": 60000},
        },
        "shellCommandPrefix": existing.get("shellCommandPrefix", ""),
        "sessionDir": existing.get("sessionDir", "~/.pi/agent/sessions"),
    }
    return json.dumps(merged, indent=2, sort_keys=True) + "\n"


def render_pi_gitignore() -> str:
    return """auth.json
sessions/
cache/
npm/
trust.json
*.log
"""


def render_pi_extension() -> str:
    return """// Generated by scripts/agent-harnesses.py; do not edit directly.
// Copyright: Ben Chatelain. Apache 2.0.

import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

type GuardResult = { decision: "allow" | "warn" | "deny"; reason?: string };

function guard(args: string[]): GuardResult {
  const script = join(homedir(), "scripts", "agent-harnesses.py");
  try {
    const output = execFileSync("python3", [script, "guard", "--harness", "pi", ...args], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output) as GuardResult;
  } catch (error: any) {
    const output = error?.stdout?.toString?.() || "";
    if (output) return JSON.parse(output) as GuardResult;
    return { decision: "deny", reason: "Shared guard failed closed" };
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", (_event, ctx) => {
    ctx.ui.setStatus("harness", "shared harness");
  });

  pi.on("tool_call", async (event) => {
    let result: GuardResult = { decision: "allow" };
    if (event.toolName === "bash") {
      result = guard(["--tool", "bash", "--command", String(event.input.command || "")]);
    } else if (event.toolName === "write" || event.toolName === "edit") {
      const path = String(event.input.file_path || event.input.path || "");
      const content = String(event.input.content || event.input.new_string || "");
      result = guard(["--tool", event.toolName, "--path", path, "--content", content]);
    }
    if (result.decision === "deny") return { block: true, reason: result.reason || "Blocked by shared harness guard" };
    return undefined;
  });

  pi.registerCommand("harness-agents", {
    description: "List shared specialist agents",
    handler: async (_args, ctx) => {
      ctx.ui.notify("Shared specialist agents are registered in ~/.pi/agent/agents.json", "info");
    },
  });

  pi.registerTool({
    name: "harness_agent_registry",
    label: "Harness Agents",
    description: "Return the shared specialist agent registry.",
    parameters: Type.Object({}),
    async execute() {
      return {
        content: [{ type: "text", text: "Read ~/.pi/agent/agents.json for shared specialist agent definitions." }],
        details: { path: "~/.pi/agent/agents.json" },
      };
    },
  });
}
"""


def build_manifest() -> dict[str, Any]:
    inventory = build_inventory()
    commands = inventory["commands"]
    agents = inventory["agents"]
    features = [
        feature(
            "instructions.global",
            "instructions",
            "p0",
            "Global harness instructions load for every session.",
            [display_path(SHARED / "instructions.md")],
            "python3 scripts/agent-harnesses.py validate",
            complete_shared(["claude", "codex", "opencode", "pi"]),
        ),
        feature(
            "skills.shared",
            "skills",
            "p0",
            "Shared skills load from ~/.agents/skills.",
            ["~/.agents/skills"],
            "python3 scripts/agent-harnesses.py inventory --json",
            complete_shared(["claude", "codex", "opencode", "pi"]),
        ),
        feature(
            "commands.active",
            "commands",
            "p0",
            "The 22 active commands are available through generated native prompts.",
            [display_path(SHARED / "commands")],
            "python3 scripts/agent-harnesses.py inventory --json",
            {
                "claude": state(
                    "complete",
                    "native",
                    [display_path(COMMAND_SOURCE)],
                    "source commands",
                ),
                "codex": state(
                    "partial",
                    "adapter",
                    [display_path(SHARED / "commands")],
                    "Codex consumes commands as skills/config, not Claude slash files",
                    "Add native Codex command generation if/when file format stabilizes",
                ),
                "opencode": state(
                    "complete",
                    "adapter",
                    [
                        display_path(OPEN_CODE / "commands"),
                        display_path(OPEN_CODE / "opencode.jsonc"),
                    ],
                    "generated command templates",
                ),
                "pi": state(
                    "complete",
                    "adapter",
                    [display_path(PI_AGENT / "prompts")],
                    "generated prompt templates",
                ),
            },
        ),
        feature(
            "agents.specialists",
            "agents",
            "p0",
            "Six specialist agents are represented for delegation.",
            [display_path(SHARED / "agents")],
            "python3 scripts/agent-harnesses.py inventory --json",
            {
                "claude": state(
                    "complete",
                    "native",
                    [display_path(ROOT / ".claude" / "agents")],
                    "native Claude agents include these plus additional specialists",
                ),
                "codex": state(
                    "complete",
                    "native",
                    [display_path(AGENT_SOURCE)],
                    "native Codex TOML agents",
                ),
                "opencode": state(
                    "complete",
                    "adapter",
                    [
                        display_path(OPEN_CODE / "agents"),
                        display_path(OPEN_CODE / "opencode.jsonc"),
                    ],
                    "generated agent config",
                ),
                "pi": state(
                    "partial",
                    "emulated",
                    [
                        display_path(PI_AGENT / "agents.json"),
                        display_path(PI_AGENT / "extensions" / "harness.ts"),
                    ],
                    "Pi uses an extension-backed registry rather than static native agent files",
                    "Wire full subprocess delegation after choosing model/session policy",
                ),
            },
        ),
        feature(
            "hooks.safety",
            "hooks",
            "p0",
            "Dangerous commands, protected writes, and secret-like content are blocked consistently.",
            [display_path(SHARED / "hooks" / "safety.py")],
            "bats tests/agent-harnesses.bats",
            complete_adapter(["claude", "codex", "opencode", "pi"]),
        ),
        feature(
            "mcp.code_review_graph",
            "mcp/tools",
            "p1",
            "code-review-graph is exposed as a tool capability.",
            [
                display_path(ROOT / ".codex" / "config.toml"),
                display_path(OPEN_CODE / "opencode.jsonc"),
            ],
            "python3 scripts/agent-harnesses.py inventory --json",
            {
                "claude": state(
                    "partial",
                    "native",
                    [display_path(ROOT / ".claude" / "settings.json")],
                    "Claude has hook-based graph updates but no tracked MCP entry in this slice",
                    "Add/verify native Claude MCP registration",
                ),
                "codex": state(
                    "complete",
                    "native",
                    [display_path(ROOT / ".codex" / "config.toml")],
                    "native MCP server configured",
                ),
                "opencode": state(
                    "complete",
                    "native",
                    [display_path(OPEN_CODE / "opencode.jsonc")],
                    "native MCP local server configured",
                ),
                "pi": state(
                    "partial",
                    "emulated",
                    [display_path(PI_AGENT / "extensions" / "harness.ts")],
                    "generic MCP transport is not configured; extension tools track capability",
                    "Implement direct MCP bridge if Pi exposes stable transport",
                ),
            },
        ),
        feature(
            "sessions.compaction",
            "sessions/compaction",
            "p1",
            "Compaction preserves modified files, branch, pending work, and test state.",
            [display_path(SHARED / "hooks" / "contract.json")],
            "python3 scripts/agent-harnesses.py validate",
            {
                "claude": state(
                    "complete",
                    "native",
                    [display_path(ROOT / ".claude" / "settings.json")],
                    "native PreCompact hook",
                ),
                "codex": state(
                    "complete",
                    "native",
                    [display_path(ROOT / ".codex" / "hooks.json")],
                    "native PreCompact hook",
                ),
                "opencode": state(
                    "complete",
                    "adapter",
                    [display_path(OPEN_CODE / "plugins" / "harness.ts")],
                    "plugin compaction hook",
                ),
                "pi": state(
                    "complete",
                    "native",
                    [display_path(PI_AGENT / "settings.json")],
                    "native compaction settings plus extension status",
                ),
            },
        ),
        feature(
            "maintenance.audit",
            "maintenance",
            "p1",
            "Parity can be generated, checked, and audited deterministically.",
            [
                display_path(ROOT / "scripts" / "agent-harnesses.py"),
                display_path(ROOT / "docs" / "agent-harnesses.json"),
            ],
            "just harness-check",
            complete_shared(["claude", "codex", "opencode", "pi"]),
        ),
    ]

    return {
        "schema": 1,
        "verified_date": VERIFIED_DATE,
        "summary": {
            "commands": len(commands),
            "agents": len(agents),
            "skills": inventory["skills"]["count"],
            "capabilities": inventory["capabilities"],
        },
        "harnesses": {
            "claude": {"role": "supported peer"},
            "codex": {"role": "supported peer"},
            "opencode": {"role": "new port"},
            "pi": {"role": "new port"},
        },
        "features": features,
    }


def feature(
    feature_id: str,
    category: str,
    priority: str,
    desired_behavior: str,
    canonical_artifacts: list[str],
    verification_command: str,
    harnesses: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    return {
        "id": feature_id,
        "category": category,
        "priority": priority,
        "desired_behavior": desired_behavior,
        "canonical_artifacts": canonical_artifacts,
        "verification_command": verification_command,
        "harnesses": harnesses,
    }


def state(
    state_name: str,
    mode: str,
    paths: list[str],
    gap_reason: str = "",
    next_action: str = "",
) -> dict[str, Any]:
    return {
        "state": state_name,
        "mode": mode,
        "paths": paths,
        "verified": {"version": "local", "date": VERIFIED_DATE},
        "gap_reason": gap_reason,
        "next_action": next_action,
    }


def complete_shared(harnesses: list[str]) -> dict[str, dict[str, Any]]:
    return {
        harness: state("complete", "shared", [display_path(SHARED)])
        for harness in harnesses
    }


def complete_adapter(harnesses: list[str]) -> dict[str, dict[str, Any]]:
    return {
        harness: state(
            "complete", "adapter", [display_path(SHARED / "hooks" / "safety.py")]
        )
        for harness in harnesses
    }


def render_manifest_markdown(manifest: dict[str, Any]) -> str:
    lines = [
        "# Agent Harness Parity",
        "",
        MANAGED_HEADER,
        "",
        f"Verified date: {manifest['verified_date']}",
        "",
        "| Feature | Category | Priority | Claude | Codex | OpenCode | Pi | Next action |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for item in manifest["features"]:
        states = item["harnesses"]
        next_actions = "; ".join(
            sorted(
                {
                    state_data.get("next_action", "")
                    for state_data in states.values()
                    if state_data.get("next_action", "")
                }
            )
        )
        lines.append(
            "| {id} | {category} | {priority} | {claude} | {codex} | {opencode} | {pi} | {next_action} |".format(
                id=item["id"],
                category=item["category"],
                priority=item["priority"],
                claude=format_state(states["claude"]),
                codex=format_state(states["codex"]),
                opencode=format_state(states["opencode"]),
                pi=format_state(states["pi"]),
                next_action=next_actions or "-",
            )
        )
    lines.append("")
    return "\n".join(lines)


def format_state(value: dict[str, Any]) -> str:
    return f"{value['state']} / {value['mode']}"


def slim_agents(agents: list[dict[str, Any]]) -> list[dict[str, str]]:
    return [
        {
            "id": agent["id"],
            "description": agent["description"],
            "shared": agent["shared"],
        }
        for agent in agents
    ]


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines()
    end_index = None
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_index = index
            break
    if end_index is None:
        return {}, text

    data: dict[str, str] = {}
    for line in lines[1:end_index]:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip().strip('"').strip("'")
        data[key.strip()] = value
    return data, "\n".join(lines[end_index + 1 :])


def first_nonempty_line(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip(" #")
        if stripped and stripped != "---" and ":" not in stripped:
            return stripped
    return ""


def command_version(command: list[str]) -> str:
    if not shutil.which(command[0]):
        return ""
    result = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return ""
    return result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""


def display_path(path: Path) -> str:
    try:
        rel = path.resolve().relative_to(HOME)
    except ValueError:
        return str(path)
    return "~/" + rel.as_posix()


if __name__ == "__main__":
    raise SystemExit(main())
