#!/usr/bin/env python3
"""Inventory, generate, validate, and audit shared agent harness parity.

Copyright: Ben Chatelain. Apache 2.0.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

from harness_paths import (
    CLI_BINARIES,
    HARNESSES,
)

# The `guard` subcommand runs on every Bash/Write/Edit hook call and needs only
# json/os/sys/pathlib, the pure-data harness_paths module, plus the safety
# policy. Defer the heavier imports that only the other subcommands use so the
# hot path stays minimal (~0.06s faster per call). Non-guard invocations
# import everything eagerly, exactly as before;
#
# `provenance` shares the fast path for a second reason: `tomllib` needs Python
# 3.11+, and the interpreter on PATH under launchd and other non-login contexts
# is the system 3.9. Anything a scheduled job or a hook may call has to load
# without it.
FAST_PATH_ACTIONS = {"guard", "provenance"}
if TYPE_CHECKING or not (len(sys.argv) >= 2 and sys.argv[1] in FAST_PATH_ACTIONS):
    import argparse
    import shutil
    import subprocess

    import tomllib
    from agent_plugins import audit_plugins, configured_plugins
    from harness_capabilities import CAPABILITIES, DOMAINS, validate_registry
    from harness_docs import (
        build_state,
        render_divergence_page,
        render_domain_page,
        render_drift_page,
        render_index,
        render_plugins_page,
        render_porting_page,
    )
    from harness_docs import (
        configure as configure_doc_rendering,
    )
    from harness_drift import append_records, diff_states, load_records, run_probe
    from harness_skills import (
        MANUAL_SKILL_ADAPTERS,
        NATIVE_SKILL_ADAPTERS,
        is_generated_pointer,
        render_antigravity_skill,
        render_claude_skill,
        render_codex_skill,
        render_cursor_skill,
        render_opencode_skill,
    )
    from harness_skills import (
        configure as configure_skill_rendering,
    )

_IS_GUARD = len(sys.argv) >= 2 and sys.argv[1] == "guard"


sys.dont_write_bytecode = True

HOME = Path(os.environ.get("HOME", str(Path.home()))).resolve()
ROOT = HOME
SHARED = ROOT / ".agents" / "harness"
# Every path render_all() writes, mapped to the hand-written file behind it. The
# `guard` hot path reads this instead of calling render_all(), which would render
# every artifact on every tool call.
GENERATED_MANIFEST = SHARED / "generated-paths.json"
GENERATOR_PATH = ROOT / "scripts" / "agent-harnesses.py"
COMMAND_SOURCE = ROOT / ".claude" / "commands"
AGENT_SOURCE = ROOT / ".codex" / "agents"
SKILL_SOURCE = ROOT / ".agents" / "skills"
CLAUDE_SKILLS = ROOT / ".claude" / "skills"
CODEX_SKILLS = ROOT / ".codex" / "skills"
OPEN_CODE = ROOT / ".config" / "opencode"
OPEN_CODE_SKILLS = OPEN_CODE / "skills"
PI_AGENT = ROOT / ".pi" / "agent"
OMP_AGENT = ROOT / ".omp" / "agent"
ANTIGRAVITY = ROOT / ".gemini" / "antigravity-cli"
ANTIGRAVITY_HARNESS = SHARED / "adapters" / "antigravity"
ANTIGRAVITY_COMMANDS = ANTIGRAVITY_HARNESS / "commands"
CURSOR = ROOT / ".cursor"
CURSOR_HARNESS = SHARED / "adapters" / "cursor"
CURSOR_PLUGIN = CURSOR_HARNESS / ".cursor-plugin"
CURSOR_RULES = CURSOR_HARNESS / "rules"
GROK = ROOT / ".grok"
CRUSH = ROOT / ".config" / "crush"
HARNESS_DOCS = ROOT / "docs" / "harness"
OBSERVED_PATH = HARNESS_DOCS / "observed.json"
VERSIONS_PATH = HARNESS_DOCS / "versions.json"
DRIFT_PATH = HARNESS_DOCS / "drift.jsonl"
MANAGED_HEADER = (
    "<!-- Generated by scripts/agent-harnesses.py; do not edit directly. -->"
)

COMPACTION_PRESERVATION = """# Context Compaction Preservation

When compacting or resuming a session, preserve and carry forward:

- The complete list of modified files, with paths.
- The current Git branch and uncommitted changes.
- Pending tasks and TODO items, including blockers.
- Test commands run, results, and failures.
- Key architectural decisions and constraints made during the session.

Do not claim work is complete until the preserved task state confirms that all actionable work is finished and verification evidence is available.
"""

sys.path.insert(0, str(SHARED / "hooks"))
try:
    from safety import GuardDecision, evaluate  # type: ignore
except ImportError as exc:  # pragma: no cover - only hit before installation
    GuardDecision = None
    evaluate = None
    SAFETY_IMPORT_ERROR = exc
else:
    SAFETY_IMPORT_ERROR = None


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="action", required=True)

    inventory_parser = subparsers.add_parser(
        "inventory", help="Print discovered harness inventory"
    )
    inventory_parser.add_argument("--json", action="store_true", help="Emit JSON")

    generate_parser = subparsers.add_parser(
        "generate", help="Generate shared/native harness artifacts"
    )
    generate_parser.add_argument(
        "--check", action="store_true", help="Fail if generated artifacts are stale"
    )

    subparsers.add_parser(
        "validate", help="Validate manifest, generated artifacts, and local discovery"
    )

    audit_parser = subparsers.add_parser("audit", help="Print version and parity audit")
    audit_parser.add_argument("--json", action="store_true", help="Emit JSON")

    guard_parser = subparsers.add_parser(
        "guard", help="Evaluate a normalized tool call"
    )
    guard_parser.add_argument("--harness", choices=HARNESSES, required=True)
    guard_parser.add_argument("--tool", required=True)
    guard_parser.add_argument("--command", dest="shell_command", default="")
    guard_parser.add_argument("--path", default="")
    guard_parser.add_argument("--content", default="")
    guard_parser.add_argument("--cwd", default=str(ROOT))

    provenance_parser = subparsers.add_parser(
        "provenance", help="Report whether a path is generated, source, or neither"
    )
    provenance_parser.add_argument("--path", required=True)
    provenance_parser.add_argument("--json", action="store_true", help="Emit JSON")
    verify_parser = subparsers.add_parser(
        "verify", help="Verify harness artifacts are discoverable"
    )
    verify_parser.add_argument(
        "--harness", choices=HARNESSES, help="Check specific harness"
    )

    probe_parser = subparsers.add_parser(
        "probe", help="Re-run capability probes, record versions, append drift"
    )
    probe_parser.add_argument(
        "--harness", choices=HARNESSES, help="Probe a single harness"
    )
    drift_parser = subparsers.add_parser(
        "drift", help="Print recorded capability drift, newest first"
    )
    drift_parser.add_argument("--limit", type=int, default=20)
    drift_parser.add_argument("--harness", choices=HARNESSES)

    args = parser.parse_args()
    if args.action == "inventory":
        return command_inventory(json_output=args.json)
    if args.action == "generate":
        return command_generate(check=args.check)
    if args.action == "validate":
        return command_validate()
    if args.action == "audit":
        return command_audit(json_output=args.json)
    if args.action == "verify":
        harness = getattr(args, "harness", None)
        return command_verify(harness=harness)
    if args.action == "probe":
        return command_probe(harness=args.harness)
    if args.action == "drift":
        return command_drift(limit=args.limit, harness=args.harness)

    if args.action == "guard":
        return command_guard(args)
    if args.action == "provenance":
        return command_provenance(args)
    raise AssertionError(args.action)


def command_inventory(*, json_output: bool) -> int:
    inventory = build_inventory()
    if json_output:
        print(json.dumps(inventory, indent=2, sort_keys=True))
    else:
        print(f"commands: {len(inventory['commands'])}")
        print(f"agents: {len(inventory['agents'])}")
        print(f"skills: {inventory['skills']['count']}")
        print("capabilities: " + ", ".join(inventory["capabilities"]))
        print(
            "plugins: "
            + ", ".join(
                f"{harness}={len(plugins)}"
                for harness, plugins in inventory["plugins"].items()
            )
        )
    return 0


# Directories that hold one generated file per command/agent/skill; files here
# that render_all() no longer produces are orphans and must be pruned.
GENERATED_ITEM_ROOTS = [
    (SHARED / "commands", "*.md"),
    (SHARED / "agents", "*.toml"),
    (OPEN_CODE / "commands", "*.md"),
    (OPEN_CODE / "agents", "*.md"),
    (PI_AGENT / "prompts", "*.md"),
    (PI_AGENT / "agents", "*.md"),
    (ANTIGRAVITY_COMMANDS, "*.md"),
    (ANTIGRAVITY_HARNESS / "agents", "*.md"),
    (CURSOR_HARNESS / "commands", "*.md"),
    (CURSOR_HARNESS / "agents", "*.md"),
    (OMP_AGENT / "agents", "*.md"),
    (GROK / "agents", "*.md"),
    # A domain page left behind after a DOMAINS key is renamed is an orphan.
    # observed.json, versions.json, and drift.jsonl are not *.md and so are
    # correctly untouched by find_orphans().
    (HARNESS_DOCS, "*.md"),
]


def find_orphans(expected: dict[Path, str]) -> list[Path]:
    orphans: list[Path] = []
    for root, pattern in GENERATED_ITEM_ROOTS:
        if not root.is_dir():
            continue
        for path in sorted(root.rglob(pattern)):
            if path not in expected:
                orphans.append(path)
    return orphans


def command_generate(*, check: bool) -> int:
    expected = render_all()
    stale: list[Path] = []
    obsolete = find_obsolete_skill_wrappers(expected)

    for path, content in expected.items():
        if path.exists() and path.read_text() == content:
            continue
        stale.append(path)

    orphans = find_orphans(expected)

    if check:
        for path in stale:
            print(f"stale: {display_path(path)}", file=sys.stderr)
        for path in orphans:
            print(f"orphan: {display_path(path)}", file=sys.stderr)
        for path in obsolete:
            print(f"obsolete: {display_path(path)}", file=sys.stderr)
        return 1 if stale or orphans or obsolete else 0

    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    roots = {root for root, _ in GENERATED_ITEM_ROOTS}
    for path in orphans:
        path.unlink()
        parent = path.parent
        while parent not in roots and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent

    for path in obsolete:
        path.unlink()
        try:
            path.parent.rmdir()
        except OSError:
            pass
    return 0


def find_obsolete_skill_wrappers(expected: dict[Path, str]) -> list[Path]:
    expected_paths = set(expected)
    obsolete: list[Path] = []
    adapters = [
        (ANTIGRAVITY_HARNESS / "skills", render_antigravity_skill),
        (CURSOR_HARNESS / "skills", render_cursor_skill),
    ]

    for root, render in adapters:
        if not root.is_dir() or root.is_symlink():
            continue
        for path in root.glob("*/SKILL.md"):
            if (
                path in expected_paths
                or path.is_symlink()
                or path.parent.is_symlink()
                or not path.is_file()
            ):
                continue
            if is_generated_pointer(path.read_text(), path.parent.name):
                obsolete.append(path)

    return sorted(obsolete)


def command_validate() -> int:
    errors: list[str] = []
    inventory = build_inventory()
    if len(inventory["commands"]) != 26:
        errors.append(
            f"expected 26 active commands, found {len(inventory['commands'])}"
        )
    if len(inventory["agents"]) != 6:
        errors.append(f"expected 6 specialist agents, found {len(inventory['agents'])}")
    if inventory["skills"]["count"] < 1:
        errors.append("expected shared skills in .agents/skills")
    errors.extend(validate_registry())
    if command_generate(check=True) != 0:
        errors.append("generated artifacts are stale")

    for config in (
        OPEN_CODE / "opencode.jsonc",
        PI_AGENT / "settings.json",
        ROOT / "docs" / "agent-harnesses.json",
        ANTIGRAVITY_HARNESS / "plugin.json",
        ANTIGRAVITY_HARNESS / "hooks" / "hooks.json",
        ANTIGRAVITY_HARNESS / "mcp.json",
        CURSOR_HARNESS / "hooks" / "hooks.json",
        CURSOR_HARNESS / "mcp.json",
        GROK / "hooks" / "harness-guard.json",
        # Absent until the first `probe` run, so parsed only once written.
        *(path for path in (OBSERVED_PATH, VERSIONS_PATH) if path.exists()),
    ):
        try:
            json.loads(config.read_text())
        except Exception as exc:  # noqa: BLE001 - report all parse failures
            errors.append(
                f"{display_path(config)} is not valid JSON/JSONC subset: {exc}"
            )

    if DRIFT_PATH.exists():
        for number, line in enumerate(DRIFT_PATH.read_text().splitlines(), start=1):
            if not line.strip():
                continue
            try:
                json.loads(line)
            except json.JSONDecodeError:
                errors.append(
                    f"{display_path(DRIFT_PATH)} line {number} is not valid JSON"
                )

    if shutil.which("opencode"):
        result = subprocess.run(
            ["opencode", "debug", "config", "--pure"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            errors.append("opencode debug config --pure failed")

    if shutil.which("pi"):
        result = subprocess.run(
            ["pi", "list", "--no-approve"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            errors.append("pi list --no-approve failed")

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("Agent harness parity checks passed")
    return 0


def command_audit(*, json_output: bool) -> int:
    inventory = build_inventory()
    state_path = ROOT / "docs" / "agent-harnesses.json"
    state = (
        json.loads(state_path.read_text())
        if state_path.exists()
        else build_state(
            observed=read_json(OBSERVED_PATH, {}),
            versions=read_json(VERSIONS_PATH, {}),
            plugins=inventory["plugins"],
        )
    )
    cells = [
        (capability["id"], slug, cell)
        for capability in state["capabilities"]
        for slug, cell in sorted(capability["cells"].items())
    ]
    audit = {
        "coverage": state["coverage"],
        "versions": {
            slug: command_version([CLI_BINARIES[slug], "--version"])
            for slug in HARNESSES
        },
        "partial": [
            {
                "id": capability_id,
                "harness": slug,
                "reason": cell["note"],
                "next_action": cell["next_action"],
            }
            for capability_id, slug, cell in cells
            if cell["parity"] in {"partial", "blocked"}
        ],
        # Kept apart from `partial` on purpose: a permanent divergence is not
        # owed work and must never read as a gap.
        "divergent": [
            {"id": capability_id, "harness": slug, "divergence": cell["divergence"]}
            for capability_id, slug, cell in cells
            if cell["parity"] == "divergent"
        ],
        "plugins": audit_plugins(inventory["plugins"]),
    }
    if json_output:
        print(json.dumps(audit, indent=2, sort_keys=True))
    else:
        print("# Agent Harness Audit")
        print()
        print(
            f"Coverage: {audit['coverage']['verified']}/{audit['coverage']['total']}"
        )
        print()
        for harness, version in audit["versions"].items():
            print(f"- {harness}: {version or 'not installed'}")
        print()
        print("## Native Plugins")
        print()
        for harness, state_data in audit["plugins"]["observed"].items():
            if state_data["available"]:
                print(f"- {harness}: {len(state_data['plugins'])} observed")
            else:
                print(f"- {harness}: unavailable ({state_data['error']})")
        for item in audit["plugins"]["drift"]:
            print(
                "- {harness} {id}: {field} configured={configured} "
                "observed={observed}".format(**item)
            )
        print()
        print("## Open Items")
        for item in audit["partial"]:
            print(f"- {item['id']} ({item['harness']}): {item['next_action']}")
        print()
        print("## Permanent Divergences")
        if audit["divergent"]:
            for item in audit["divergent"]:
                print(f"- {item['id']} ({item['harness']}): {item['divergence']}")
        else:
            print("- none")
    return 0


def command_probe(*, harness: str | None = None) -> int:
    """Re-run declared probes, record CLI versions, and append drift.

    The only mutator of committed probe state. A failing probe is data, not a
    build break, so this exits 0 either way; `validate` is where a hard failure
    belongs.
    """
    from datetime import datetime, timezone

    # Local calendar date: Evidence.date records the day the claim was checked.
    today = datetime.now(tz=timezone.utc).astimezone().date().isoformat()
    slugs = [harness] if harness else list(HARNESSES)
    previous_observed = read_json(OBSERVED_PATH, {})
    previous_versions = read_json(VERSIONS_PATH, {})

    versions: dict[str, dict[str, str]] = {
        slug: dict(value) for slug, value in previous_versions.items()
    }
    rechecked: list[tuple[str, str, str]] = []
    for slug in slugs:
        prior = previous_versions.get(slug, {})
        was = prior.get("version", "")
        now = command_version([CLI_BINARIES[slug], "--version"])
        changed = bool(was) and was != now
        versions[slug] = {
            # first_seen is set once, on the first run that records a version,
            # and never rewritten.
            "first_seen": prior.get("first_seen", "") or (today if now else ""),
            "previous": was if changed else prior.get("previous", ""),
            "version": now,
        }
        if changed:
            rechecked.append((slug, was, now))

    observed: dict[str, dict[str, dict[str, str]]] = {
        slug: {key: dict(value) for key, value in entries.items()}
        for slug, entries in previous_observed.items()
    }
    tally = {"pass": 0, "fail": 0, "unavailable": 0}
    for slug in slugs:
        probed: dict[str, dict[str, str]] = {}
        for capability in CAPABILITIES:
            cell = capability.cells.get(slug)
            if cell is None:
                continue
            record = {
                "mode": cell.mode,
                "parity": cell.parity,
                "surface": cell.surface,
            }
            if cell.probe is not None:
                outcome = run_probe(slug, cell.probe, home=ROOT)
                record["date"] = today
                record["detail"] = outcome["detail"]
                record["result"] = outcome["result"]
                tally[outcome["result"]] += 1
                print(
                    f"{outcome['result']:>11}  {slug} {capability.id}: "
                    f"{outcome['detail']}"
                )
            probed[capability.id] = record
        observed[slug] = probed

    records = diff_states(
        {
            "observed": previous_observed,
            "versions": {
                slug: value.get("version", "")
                for slug, value in previous_versions.items()
            },
        },
        {
            "observed": observed,
            "versions": {slug: value["version"] for slug, value in versions.items()},
        },
        date=today,
    )
    append_records(DRIFT_PATH, records)
    write_json(OBSERVED_PATH, observed)
    write_json(VERSIONS_PATH, versions)

    print()
    print(
        f"probes: {tally['pass']} pass, {tally['fail']} fail, "
        f"{tally['unavailable']} unavailable"
    )
    print(f"drift records appended: {len(records)}")
    for slug, was, now in rechecked:
        print(
            f"re-research {slug}: run the harness-research skill for {now} "
            f"(was {was})"
        )
    return 0


def command_drift(*, limit: int = 20, harness: str | None = None) -> int:
    """Print recorded drift, newest first."""
    records = load_records(DRIFT_PATH)
    if harness:
        records = [record for record in records if record.get("harness") == harness]
    if not records:
        print("no drift recorded")
        return 0
    for record in records[:limit]:
        print(
            f"{record.get('date', '-')} {record.get('harness', '-')} "
            f"{record.get('capability', '-')} {record.get('field', '-')}: "
            f"{record.get('from', '')} -> {record.get('to', '')}"
        )
    return 0


def write_json(path: Path, payload: Any) -> None:
    """Write committed JSON state deterministically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")


def command_verify(*, harness: str | None = None) -> int:
    """Verify harness artifacts are discoverable by each CLI."""
    import shutil
    import subprocess

    # Check file existence and CLI discovery per harness
    checks = {
        "omp": [
            (OMP_AGENT / "APPEND_SYSTEM.md", "APPEND_SYSTEM.md exists"),
            (OMP_AGENT / "agents", "agents directory exists"),
        ],
        "claude": [
            (COMMAND_SOURCE, "commands directory exists"),
            (ROOT / ".claude" / "agents", "agents directory exists"),
        ],
        "antigravity": [
            (ANTIGRAVITY_HARNESS / "plugin.json", "plugin.json exists"),
            (ANTIGRAVITY_HARNESS / "commands", "commands directory exists"),
        ],
        "cursor": [
            (CURSOR_RULES, "rules directory exists"),
            (CURSOR_HARNESS / "commands", "commands directory exists"),
        ],
        "grok": [
            (GROK / "config.toml", "config.toml exists"),
            (GROK / "rules" / "shared-harness.md", "rules file exists"),
            (GROK / "hooks" / "harness-guard.json", "guard hook exists"),
            (GROK / "scripts" / "harness-guard.py", "guard wrapper exists"),
            (GROK / "agents", "agents directory exists"),
        ],
        "crush": [
            (CRUSH / "crushrc", "crushrc exists"),
            (CRUSH / "shared-harness.md", "context file exists"),
            (CRUSH / "hooks" / "harness-guard.py", "guard wrapper exists"),
        ],
    }

    # Only verify requested harness or all if none specified
    harnesses_to_check = [harness] if harness else checks.keys()

    for hname in harnesses_to_check:
        if hname not in checks:
            print(f"Unknown harness: {hname}")
            continue

        print(f"\n{hname}:")
        for path, description in checks[hname]:
            if path.exists():
                print(f"  ✅ {description}")
            else:
                print(f"  ❌ {description} (missing)")

    # For omp, also check if agents are discoverable
    if (not harness or harness == "omp") and shutil.which("omp"):
        result = subprocess.run(
            ["omp", "task-agent", "list"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        if result.returncode == 0:
            # Count agents in output
            output = result.stdout
            agent_count = output.count("Expert") if "Expert" in output else 0
            if agent_count >= 6:
                print(f"  ✅ omp discovers {agent_count}+ agents")
            else:
                print(f"  ⚠️  omp discovered only {agent_count} agents (expected 6+)")

    return 0


def command_guard(args: argparse.Namespace) -> int:
    if evaluate is None or GuardDecision is None:
        print(
            json.dumps(
                {
                    "decision": "deny",
                    "reason": f"safety module unavailable: {SAFETY_IMPORT_ERROR}",
                }
            )
        )
        return 2

    decision = evaluate(
        args.tool,
        command=args.shell_command,
        path=args.path,
        content=args.content,
        cwd=args.cwd,
    )
    if decision.allowed and args.path:
        generated = generated_path_warning(args.tool, args.path)
        if generated:
            decision = GuardDecision("deny", generated)
    payload = {
        "harness": args.harness,
        "tool": args.tool,
        "decision": decision.decision,
        "reason": decision.reason,
    }
    print(json.dumps(payload, sort_keys=True))
    return 0 if decision.allowed else 2


def load_generated_manifest() -> dict[str, dict[str, str]]:
    """Read GENERATED_MANIFEST, or return {} when it is missing or unreadable.

    Fails open on purpose: a missing manifest must not wedge every write in every
    harness. `just harness-check` is what catches the manifest going stale.
    """

    try:
        data = json.loads(GENERATED_MANIFEST.read_text())
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def generated_relpath(path: str) -> str | None:
    """Return the manifest key for `path`, or None when it is not generated.

    Matches on the tail of the path rather than on equality so that a copy of the
    repository checked out as a worktree — where the same artifact lives under a
    different prefix — is still recognized as generated.
    """

    manifest = load_generated_manifest()
    if not manifest:
        return None
    candidate = Path(os.path.expanduser(path))
    try:
        candidate = candidate.resolve()
    except OSError:
        pass
    posix = candidate.as_posix()
    for key in manifest:
        rel = key.removeprefix("~/")
        if posix == rel or posix.endswith("/" + rel):
            return key
    return None


def generated_path_warning(tool: str, path: str) -> str:
    """Explain why `path` must not be written, when it is a generated artifact."""

    if tool.lower().strip() not in {
        "write",
        "edit",
        "multiedit",
        "file_write",
        "file_edit",
    }:
        return ""
    key = generated_relpath(path)
    if key is None:
        return ""
    source = load_generated_manifest().get(key, {}).get("source") or ""
    target = f"Edit {source} instead" if source else "Edit its source instead"
    return (
        f"{key} is generated by scripts/agent-harnesses.py and will be "
        f"overwritten by the next `just harness-generate`. {target}, then "
        "regenerate."
    )


def command_provenance(args: argparse.Namespace) -> int:
    key = generated_relpath(args.path)
    resolved = display_path(Path(os.path.expanduser(args.path)))
    if key is not None:
        kind = "generated"
        source = load_generated_manifest().get(key, {}).get("source") or ""
    elif resolved in {
        display_path(GENERATOR_PATH),
        display_path(SHARED / "hooks" / "safety.py"),
    }:
        kind, source = "generator", ""
    elif any(
        _is_within(args.path, root)
        for root in (COMMAND_SOURCE, AGENT_SOURCE, SKILL_SOURCE)
    ):
        kind, source = "source", ""
    else:
        kind, source = "other", ""

    payload = {"path": resolved, "kind": kind, "source": source}
    if args.json:
        print(json.dumps(payload, sort_keys=True))
    else:
        print(f"{kind}\t{resolved}" + (f"\t{source}" if source else ""))
    return 0


def _is_within(path: str, root: Path) -> bool:
    try:
        Path(os.path.expanduser(path)).resolve().relative_to(root.resolve())
    except (OSError, ValueError):
        return False
    return True


def build_inventory(*, include_prompts: bool = False) -> dict[str, Any]:
    commands = discover_commands()
    agents = discover_agents(include_prompts=include_prompts)
    skills = sorted(
        str(path.relative_to(SKILL_SOURCE).parent)
        for path in SKILL_SOURCE.glob("*/SKILL.md")
    )
    capabilities = ["shared-skills"]
    if (OPEN_CODE / "plugins" / "harness.ts").exists():
        capabilities.append("opencode-plugin")
    if (PI_AGENT / "extensions" / "harness.ts").exists():
        capabilities.append("pi-extension")

    return {
        "commands": commands,
        "agents": agents,
        "skills": {"count": len(skills), "paths": skills},
        "capabilities": capabilities,
        "plugins": configured_plugins(ROOT),
    }


def discover_commands() -> list[dict[str, Any]]:
    commands: list[dict[str, Any]] = []
    for path in sorted(COMMAND_SOURCE.rglob("*.md")):
        rel = path.relative_to(COMMAND_SOURCE)
        command_id = rel.with_suffix("").as_posix()
        body = path.read_text()
        frontmatter, _ = parse_frontmatter(body)
        commands.append(
            {
                "id": command_id,
                "native": command_id.replace("/", ":"),
                "description": frontmatter.get(
                    "description", first_nonempty_line(body)
                ),
                "argument_hint": frontmatter.get("argument-hint")
                or frontmatter.get("argument_hint", ""),
                "source": display_path(path),
                "shared": display_path(SHARED / "commands" / rel),
            }
        )
    return commands


def discover_agents(*, include_prompts: bool = False) -> list[dict[str, Any]]:
    agents: list[dict[str, Any]] = []
    for path in sorted(AGENT_SOURCE.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        name = data.get("name", path.stem)
        agent = {
            "id": name,
            "description": data.get("description", ""),
            "source": display_path(path),
            "shared": display_path(SHARED / "agents" / f"{name}.toml"),
        }
        if include_prompts:
            agent["prompt"] = data.get("developer_instructions", "")
        agents.append(agent)
    return agents


def read_json(path: Path, default: Any) -> Any:
    """Read committed JSON state, falling back so a fresh checkout can render."""
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return default


def render_all() -> dict[Path, str]:
    configure_skill_rendering(managed_header=MANAGED_HEADER, skill_source=SKILL_SOURCE)
    configure_doc_rendering(managed_header=MANAGED_HEADER)
    inventory = build_inventory(include_prompts=True)
    commands = inventory["commands"]
    agents = inventory["agents"]
    # Reverse map from each generated artifact to the hand-written file it came
    # from. Populated by diffing the keys of `rendered` after each loop iteration
    # rather than by restating the target paths, so a new adapter cannot be added
    # without its provenance following. Serialized as GENERATED_MANIFEST below.
    provenance: dict[Path, str] = {}
    # One build of the capability state, reused by the index, every domain page,
    # and the JSON. Reads committed probe state only: render_all() must stay
    # pure, because `generate --check` is what parity checking relies on for
    # idempotence. `probe` is the only mutator.
    state = build_state(
        observed=read_json(OBSERVED_PATH, {}),
        versions=read_json(VERSIONS_PATH, {}),
        plugins=inventory["plugins"],
    )
    drift_records = load_records(DRIFT_PATH, limit=200)
    rendered: dict[Path, str] = {
        SHARED / "README.md": render_shared_readme(commands, agents),
        SHARED / "instructions.md": render_instructions(),
        OMP_AGENT / "APPEND_SYSTEM.md": render_omp_append_system(),
        SHARED / "hooks" / "contract.json": render_contract(),
        SHARED / "hooks" / "safety-policy.json": render_safety_policy(),
        ROOT / "docs" / "agent-harnesses.json": json.dumps(
            state, indent=2, sort_keys=True
        )
        + "\n",
        ROOT / "docs" / "agent-harnesses.md": render_index(state, drift_records),
        HARNESS_DOCS / "porting.md": render_porting_page(state),
        HARNESS_DOCS / "divergence.md": render_divergence_page(state),
        HARNESS_DOCS / "drift.md": render_drift_page(state, drift_records),
        HARNESS_DOCS / "plugins.md": render_plugins_page(state),
        OPEN_CODE / "opencode.jsonc": render_opencode_config(commands, agents),
        OPEN_CODE / "plugins" / "harness.ts": render_opencode_plugin(),
        PI_AGENT / "settings.json": render_pi_settings(),
        PI_AGENT / "extensions" / "harness.ts": render_pi_extension(),
        PI_AGENT / "agents.json": json.dumps(
            {"agents": slim_agents(agents)}, indent=2, sort_keys=True
        )
        + "\n",
        ANTIGRAVITY_HARNESS / "plugin.json": render_antigravity_plugin_manifest(),
        ANTIGRAVITY_HARNESS / "hooks" / "hooks.json": render_antigravity_hooks(),
        ANTIGRAVITY_HARNESS
        / "scripts"
        / "harness-guard.py": render_antigravity_guard(),
        ANTIGRAVITY_HARNESS / "mcp.json": render_antigravity_mcp(),
        CURSOR_PLUGIN / "plugin.json": render_cursor_plugin_manifest(),
        CURSOR_RULES / "shared-harness.mdc": render_cursor_rule(),
        CURSOR_HARNESS / "hooks" / "hooks.json": render_cursor_hooks(),
        CURSOR_HARNESS / "scripts" / "harness-guard.py": render_cursor_guard(),
        CURSOR_HARNESS / "mcp.json": render_cursor_mcp(),
        GROK / "config.toml": render_grok_config(),
        GROK / "rules" / "shared-harness.md": render_grok_rules(),
        GROK / "hooks" / "harness-guard.json": render_grok_hooks(),
        GROK / "scripts" / "harness-guard.py": render_grok_guard(),
        CRUSH / "crushrc": render_crush_config(),
        CRUSH / "shared-harness.md": render_crush_context(),
        CRUSH / "hooks" / "harness-guard.py": render_crush_guard(),
    }

    for domain in DOMAINS:
        rendered[HARNESS_DOCS / f"{domain}.md"] = render_domain_page(state, domain)

    for command in commands:
        source = ROOT / command["source"].replace("~/", "")
        emitted = set(rendered)
        rel = Path(command["id"] + ".md")
        rendered[SHARED / "commands" / rel] = render_shared_command(source.read_text())
        rendered[OPEN_CODE / "commands" / f"{command['native']}.md"] = (
            render_native_command(command)
        )
        rendered[PI_AGENT / "prompts" / f"{command['native']}.md"] = render_pi_prompt(
            command
        )
        rendered[ANTIGRAVITY_COMMANDS / rel] = render_antigravity_command(command)
        rendered[CURSOR_HARNESS / "commands" / rel] = render_cursor_command(command)
        record_provenance(provenance, rendered, emitted, source)

    for agent in agents:
        source = ROOT / agent["source"].replace("~/", "")
        emitted = set(rendered)
        rendered[SHARED / "agents" / f"{agent['id']}.toml"] = render_shared_agent(
            source.read_text()
        )
        rendered[OPEN_CODE / "agents" / f"{agent['id']}.md"] = render_native_agent(
            agent
        )
        rendered[PI_AGENT / "agents" / f"{agent['id']}.md"] = render_pi_agent(agent)
        rendered[ANTIGRAVITY_HARNESS / "agents" / f"{agent['id']}.md"] = (
            render_antigravity_agent(agent)
        )
        rendered[CURSOR_HARNESS / "agents" / f"{agent['id']}.md"] = render_cursor_agent(
            agent
        )
        rendered[OMP_AGENT / "agents" / f"{agent['id']}.md"] = render_omp_agent(agent)
        rendered[GROK / "agents" / f"{agent['id']}.md"] = render_grok_agent(agent)
        record_provenance(provenance, rendered, emitted, source)

    for skill_name in inventory["skills"]["paths"]:
        source = SKILL_SOURCE / skill_name / "SKILL.md"
        emitted = set(rendered)
        rendered[ANTIGRAVITY_HARNESS / "skills" / skill_name / "SKILL.md"] = (
            render_antigravity_skill(skill_name)
        )
        rendered[CURSOR_HARNESS / "skills" / skill_name / "SKILL.md"] = (
            render_cursor_skill(skill_name)
        )
        record_provenance(provenance, rendered, emitted, source)
    for skill_name in sorted(NATIVE_SKILL_ADAPTERS & set(inventory["skills"]["paths"])):
        source = SKILL_SOURCE / skill_name / "SKILL.md"
        emitted = set(rendered)
        manual_only = skill_name in MANUAL_SKILL_ADAPTERS
        rendered[CLAUDE_SKILLS / skill_name / "SKILL.md"] = render_claude_skill(
            skill_name, manual_only=manual_only
        )
        rendered[CODEX_SKILLS / skill_name / "SKILL.md"] = render_codex_skill(
            skill_name
        )
        if manual_only:
            rendered[CODEX_SKILLS / skill_name / "agents" / "openai.yaml"] = (
                render_codex_skill_policy()
            )
        rendered[OPEN_CODE_SKILLS / skill_name / "SKILL.md"] = render_opencode_skill(
            skill_name
        )
        record_provenance(provenance, rendered, emitted, source)

    # The manifest describes itself too, so `provenance` never reports a
    # generated file as untracked merely because it is the manifest.
    provenance.setdefault(GENERATED_MANIFEST, "")
    for target in rendered:
        provenance.setdefault(target, "")
    rendered[GENERATED_MANIFEST] = (
        json.dumps(
            {
                display_path(target): {"source": source}
                for target, source in sorted(
                    provenance.items(), key=lambda item: display_path(item[0])
                )
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )

    return rendered


def record_provenance(
    provenance: dict[Path, str],
    rendered: dict[Path, str],
    emitted: set[Path],
    source: Path,
) -> None:
    """Attribute every artifact added since `emitted` was captured to `source`."""

    for target in rendered.keys() - emitted:
        provenance[target] = display_path(source)


def render_shared_readme(
    commands: list[dict[str, Any]], agents: list[dict[str, Any]]
) -> str:
    return f"""# Shared Agent Harness

{MANAGED_HEADER}

This directory is the portable harness layer for Claude, Codex, OpenCode, Pi,
Antigravity, Cursor, and Grok.
It keeps command prompts, specialist agent definitions, normalized hook contracts,
and shared safety policy in one place. Native harness directories should contain
thin generated adapters or tool-specific configuration only.

## Inventory

- Commands: {len(commands)}
- Specialist agents: {len(agents)}
- Shared skills source: `~/.agents/skills`
- Safety policy: `~/.agents/harness/hooks/safety.py`

"""


def render_instructions() -> str:
    return f"""# Shared Harness Instructions

{MANAGED_HEADER}

## Licensing

- Copyright: Ben Chatelain. MIT

Always load repository instructions first, then use shared skills from
`~/.agents/skills` when a task matches a skill description. Prefer the canonical
command prompts under `~/.agents/harness/commands` and specialist agent
definitions under `~/.agents/harness/agents`.

Safety-sensitive lifecycle events must be normalized through
`~/.agents/harness/hooks/contract.json` and evaluated by the shared safety policy.
Adapters may add stricter native permissions, but they must not weaken a shared
deny decision.

## Operating Discipline

- Think before coding. Do not assume intent or constraints; ask when a choice
  materially changes scope, behavior, or risk. Surface confusion instead of
  running with a guess.
- Simplicity first. Write the minimum code that solves the problem. Do not add
  speculative abstractions.
- Surgical changes. Touch only what the user asked you to touch. Do not refactor
  adjacent code unless it is required for the requested change.
- Goal-driven execution. Define what done looks like before implementation. Use
  tests or explicit checks as success criteria, not vibes.
- Explicit configuration. When configuring a CLI tool, state every setting
  rather than leaning on its defaults. An omitted setting is an invisible
  dependency on behavior that can differ by version, platform, or machine, and
  it fails silently when the default changes. Prefer configuration that breaks
  loudly over configuration that is merely absent.

## Token Efficiency

- Be thorough in reasoning and concise in output.
- Start with the result. Skip preambles, pleasantries, and closing filler.
- Do not narrate tool use unless the user needs status or the task is long
  running.
- Return the minimum viable output that satisfies the task.
- Do not explain code, commands, or diffs unless asked or needed to clarify risk.
- Avoid re-reading files unless they changed or prior context is insufficient.
- Skip files over 100KB unless they are required for the task.
- Never invent file paths, APIs, flags, versions, package names, fields, commit
  SHAs, or resource contents. Verify before asserting.
- If a value is unknown, say so directly instead of guessing.
- Cap parallel subagents at 3 unless explicitly instructed otherwise.

## Answer Beacon

When directly answering a user question, especially inside a longer status update
or mixed task output, prefix the answer with:

💬 Answer:

Use this marker only for actual answers to user questions, not every progress
update.
"""


def render_contract() -> str:
    contract = {
        "version": 1,
        "events": {
            "session_start": {"fields": ["cwd", "session_id", "harness"]},
            "user_prompt": {"fields": ["prompt", "session_id", "harness"]},
            "tool_call": {
                "fields": [
                    "tool",
                    "command",
                    "path",
                    "content",
                    "session_id",
                    "harness",
                ]
            },
            "tool_result": {
                "fields": ["tool", "status", "output", "session_id", "harness"]
            },
            "compaction": {"fields": ["session_id", "reason", "harness"]},
            "failure": {"fields": ["tool", "error", "session_id", "harness"]},
        },
        "decisions": ["allow", "warn", "deny"],
    }
    return json.dumps(contract, indent=2, sort_keys=True) + "\n"


def render_safety_policy() -> str:
    policy = {
        "version": 1,
        "protected_paths": [
            ".env*",
            ".ssh/*",
            "*.pem",
            "*.key",
            ".aws/credentials",
            ".docker/config.json",
            ".claude/.credentials.json",
            ".codex/auth.json",
            ".omp/agent/agent.db",
            ".omp/agent/secrets.yml",
            ".pi/agent/auth.json",
            ".gemini/google_accounts.json",
            ".gemini/oauth_creds.json",
            ".gemini/antigravity-cli/installation_id",
            ".gemini/antigravity-cli/conversations/*",
            ".cursor/ai-tracking/*",
            ".grok/auth.json",
            ".grok/mcp_credentials.json",
        ],
        "blocked_command_categories": [
            "privilege-escalation",
            "destructive-filesystem",
            "device-writes",
            "pipe-to-shell",
            "obfuscated-execution",
        ],
        "secret_categories": [
            "ai-provider-key",
            "cloud-access-key",
            "vcs-token",
            "chat-token",
            "private-key",
            "password-assignment",
        ],
    }
    return json.dumps(policy, indent=2, sort_keys=True) + "\n"


def render_shared_command(source_text: str) -> str:
    return f"{MANAGED_HEADER}\n\n{source_text}"


def render_shared_agent(source_text: str) -> str:
    return f"# Generated by scripts/agent-harnesses.py; do not edit directly.\n{source_text}"


def render_native_command(command: dict[str, Any]) -> str:
    return f"""---
description: {json.dumps(command["description"])[1:-1]}
---

{MANAGED_HEADER}

Execute the shared `{command["id"]}` command prompt from:

`{command["shared"]}`

Pass user arguments through unchanged.
"""


def render_pi_prompt(command: dict[str, Any]) -> str:
    hint = (
        f'argument-hint: "{command["argument_hint"]}"\n'
        if command["argument_hint"]
        else ""
    )
    return f"""---
description: {json.dumps(command["description"])[1:-1]}
{hint}---

{MANAGED_HEADER}

Execute the shared `{command["id"]}` command prompt from:

`{command["shared"]}`

Arguments: $ARGUMENTS
"""


def render_native_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

Load the shared specialist definition from `{agent["shared"]}`.
"""


def render_antigravity_plugin_manifest() -> str:
    manifest = {
        "name": "shared-agent-harness",
        "version": "1.0.0",
        "description": "Shared agent harness adapter for Antigravity.",
        "author": {"name": "Ben Chatelain"},
        "license": "Apache-2.0",
        "keywords": ["agents", "harness", "antigravity"],
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render_antigravity_command(command: dict[str, Any]) -> str:
    return render_native_command(command)


def render_antigravity_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

Load the shared specialist definition from `{agent["shared"]}`.
"""


def render_codex_skill_policy() -> str:
    return "policy:\n  allow_implicit_invocation: false\n"


def render_antigravity_hooks() -> str:
    hooks = {
        "version": 1,
        "hooks": {
            "tool_call": [
                {
                    "command": "python3 scripts/harness-guard.py",
                    "description": "Evaluate shell, write, and edit calls with the shared harness guard.",
                }
            ],
            "compaction": [
                {
                    "append": "Preserve modified files, current branch, pending tasks, test results, and harness parity gaps."
                }
            ],
        },
    }
    return json.dumps(hooks, indent=2, sort_keys=True) + "\n"


def render_antigravity_guard() -> str:
    return """#!/usr/bin/env python3
\"\"\"Antigravity wrapper for the shared agent harness guard.

Copyright: Ben Chatelain. Apache 2.0.
\"\"\"

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys


def main() -> int:
    payload = json.load(sys.stdin)
    tool = str(payload.get("tool", ""))
    command = str(payload.get("command", ""))
    path = str(payload.get("path", ""))
    content = str(payload.get("content", ""))
    cwd = str(payload.get("cwd", ""))
    script = Path.home() / "scripts" / "agent-harnesses.py"
    args = [
        "python3",
        str(script),
        "guard",
        "--harness",
        "antigravity",
        "--tool",
        tool,
        "--command",
        command,
        "--path",
        path,
        "--content",
        content,
    ]
    if cwd:
        args.extend(["--cwd", cwd])
    result = subprocess.run(
        args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    print(result.stdout, end="")
    if result.stdout:
        return result.returncode
    print(
        json.dumps(
            {
                "harness": "antigravity",
                "tool": tool,
                "decision": "deny",
                "reason": "Shared guard failed closed",
            },
            sort_keys=True,
        )
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
"""


def render_antigravity_mcp() -> str:
    mcp = {"mcpServers": {}}
    return json.dumps(mcp, indent=2, sort_keys=True) + "\n"


def render_cursor_plugin_manifest() -> str:
    manifest = {
        "name": "shared-agent-harness",
        "version": "1.0.0",
        "description": "Shared agent harness adapter for Cursor.",
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render_cursor_rule() -> str:
    return f"""---
description: Load the shared agent harness for every Cursor session.
alwaysApply: true
---

{MANAGED_HEADER}

Load repository instructions first, then follow `~/.agents/harness/instructions.md`.
Use shared skills from `~/.agents/skills` when a task matches a skill description.
Preserve modified files, current branch, pending tasks, test results, and harness parity gaps during compaction or handoff.
"""


def render_cursor_command(command: dict[str, Any]) -> str:
    return render_native_command(command)


def render_cursor_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

Load the shared specialist definition from `{agent["shared"]}` before acting.
"""


def render_cursor_hooks() -> str:
    hooks = {
        "version": 1,
        "hooks": {
            "tool_call": [
                {
                    "command": "python3 scripts/harness-guard.py",
                    "description": "Evaluate shell, write, and edit calls with the shared harness guard.",
                }
            ],
            "compaction": [
                {
                    "append": "Preserve modified files, current branch, pending tasks, test results, and harness parity gaps."
                }
            ],
        },
    }
    return json.dumps(hooks, indent=2, sort_keys=True) + "\n"


def render_cursor_guard() -> str:
    return """#!/usr/bin/env python3
\"\"\"Cursor wrapper for the shared agent harness guard.

Copyright: Ben Chatelain. Apache 2.0.
\"\"\"

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys


def main() -> int:
    payload = json.load(sys.stdin)
    tool = str(payload.get("tool", ""))
    command = str(payload.get("command", ""))
    path = str(payload.get("path", ""))
    content = str(payload.get("content", ""))
    cwd = str(payload.get("cwd", ""))
    script = Path.home() / "scripts" / "agent-harnesses.py"
    args = [
        "python3",
        str(script),
        "guard",
        "--harness",
        "cursor",
        "--tool",
        tool,
        "--command",
        command,
        "--path",
        path,
        "--content",
        content,
    ]
    if cwd:
        args.extend(["--cwd", cwd])
    result = subprocess.run(
        args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    print(result.stdout, end="")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
"""


def render_cursor_mcp() -> str:
    mcp = {"mcpServers": {}}
    return json.dumps(mcp, indent=2, sort_keys=True) + "\n"


def render_grok_config() -> str:
    return """# Generated by scripts/agent-harnesses.py; do not edit directly.

[compat.claude]
skills = true
rules = true
agents = true
mcps = true
hooks = false
sessions = true

[compat.cursor]
skills = true
rules = true
agents = true
mcps = true
hooks = false
sessions = true

[compat.codex]
sessions = true

[marketplace]
default_skills_installs_purged = true
official_marketplace_auto_installed = true

[[marketplace.sources]]
name = "xAI Official"
git = "https://github.com/xai-org/plugin-marketplace.git"
"""


def render_grok_rules() -> str:
    instructions = render_instructions()
    return f"""{instructions}

{COMPACTION_PRESERVATION}
# Git Commit Attribution

When creating any Git commit, append this trailer exactly once after a blank line:

Co-Authored-By: grokkybara[bot] <304785771+grokkybara[bot]@users.noreply.github.com>
"""


def render_grok_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

{agent["prompt"].strip()}
"""


def render_grok_hooks() -> str:
    hooks = {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash|Write|Edit|MultiEdit|run_terminal_cmd|run_terminal_command|search_replace|write_file|create_file|delete_file|Delete",
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3 $HOME/.grok/scripts/harness-guard.py",
                            "timeout": 10,
                        }
                    ],
                }
            ]
        }
    }
    return json.dumps(hooks, indent=2, sort_keys=True) + "\n"


def render_grok_guard() -> str:
    return '''#!/usr/bin/env python3
"""Grok wrapper for the shared agent harness guard.

Grok sends camelCase hook payloads (`toolName`, `toolInput`), unlike the
snake_case Claude envelope, and has no `warn` decision. Classify by the shape
of `toolInput` so an upstream tool rename cannot silently unhook the guard.

Copyright: Ben Chatelain. Apache 2.0.
"""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys

PATH_KEYS = ("file_path", "path", "target_file")
CONTENT_KEYS = ("content", "new_string", "new_text", "new_str")


def deny(reason: str) -> int:
    print(json.dumps({"decision": "deny", "reason": reason}))
    return 2


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except ValueError as exc:
        return deny(f"shared guard failed closed: unreadable hook payload ({exc})")

    tool_input = payload.get("toolInput")
    if not isinstance(tool_input, dict):
        tool_input = {}
    command = tool_input.get("command")
    command = command if isinstance(command, str) else ""
    path = ""
    for key in PATH_KEYS:
        value = tool_input.get(key)
        if isinstance(value, str) and value:
            path = value
            break
    content = "".join(
        value
        for value in (tool_input.get(key) for key in CONTENT_KEYS)
        if isinstance(value, str)
    )

    if command:
        tool = "bash"
    elif path:
        tool = "write"
    else:
        print(json.dumps({"decision": "allow"}))
        return 0

    args = [
        "python3",
        str(Path.home() / "scripts" / "agent-harnesses.py"),
        "guard",
        "--harness",
        "grok",
        "--tool",
        tool,
        "--command",
        command,
        "--path",
        path,
        "--content",
        content,
    ]
    cwd = payload.get("cwd")
    if isinstance(cwd, str) and cwd:
        args.extend(["--cwd", cwd])

    result = subprocess.run(
        args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    try:
        verdict = json.loads(result.stdout)
    except ValueError:
        detail = result.stderr.strip() or "no guard output"
        return deny(f"shared guard failed closed: {detail}")

    decision = verdict.get("decision", "deny")
    reason = verdict.get("reason", "shared guard failed closed")
    if decision == "deny":
        return deny(reason)
    if decision == "warn" and reason:
        print(reason, file=sys.stderr)
    print(json.dumps({"decision": "allow"}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_crush_config() -> str:
    return """# Generated by scripts/agent-harnesses.py; do not edit directly.

# Shared harness instructions, loaded for every session.
option global-context-path "$HOME/.config/crush/shared-harness.md"

# Shared skills. Crush's default *global* skill roots are
# ~/.config/crush/skills and ~/.config/agents/skills, so the shared root has
# to be named explicitly; only the project-relative .agents/skills is implicit.
option skill-path "$HOME/.agents/skills"

# The generated context file above carries the commit trailer. Keep crush from
# appending a second one of its own.
option attribution-trailer-style none
option attribution-generated-with false

# Normalized safety guard. Crush resolves a hook command against the process
# working directory rather than the config file, so a global hook needs an
# absolute path; python3 is invoked explicitly so the hook does not depend on
# the generated file carrying an exec bit.
hook add PreToolUse \\
  --name shared-harness-guard \\
  --matcher "^(bash|edit|write|multiedit|download)$" \\
  --command "python3 $HOME/.config/crush/hooks/harness-guard.py" \\
  --timeout 10
"""


def render_crush_context() -> str:
    instructions = render_instructions()
    return f"""{instructions}

{COMPACTION_PRESERVATION}
# Git Commit Attribution

When creating any Git commit, append this trailer exactly once after a blank line:

Co-Authored-By: Crush <crush@charm.land>
"""


def render_crush_guard() -> str:
    return '''#!/usr/bin/env python3
"""Crush wrapper for the shared agent harness guard.

Crush sends snake_case PreToolUse payloads (`tool_name`, `tool_input`) and
blocks a call on exit 2, using stderr as the deny reason. Classify by the shape
of `tool_input` so an upstream tool rename cannot silently unhook the guard.

An allowed call stays silent on purpose. Crush reads `{"decision": "allow"}` as
affirmative pre-approval that bypasses its own permission prompt, so echoing
`allow` here would weaken crush's native safety rather than add to it. Exit 0
with no stdout is crush's documented "no opinion", which falls through to the
normal permission flow.

Copyright: Ben Chatelain. Apache 2.0.
"""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys

PATH_KEYS = ("file_path", "path", "target_file")
CONTENT_KEYS = ("content", "new_string", "new_text", "new_str")


def deny(reason: str) -> int:
    print(reason, file=sys.stderr)
    return 2


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except ValueError as exc:
        return deny(f"shared guard failed closed: unreadable hook payload ({exc})")

    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        tool_input = {}
    command = tool_input.get("command")
    command = command if isinstance(command, str) else ""
    path = ""
    for key in PATH_KEYS:
        value = tool_input.get(key)
        if isinstance(value, str) and value:
            path = value
            break
    content = "".join(
        value
        for value in (tool_input.get(key) for key in CONTENT_KEYS)
        if isinstance(value, str)
    )

    if command:
        tool = "bash"
    elif path:
        tool = "write"
    else:
        return 0

    args = [
        "python3",
        str(Path.home() / "scripts" / "agent-harnesses.py"),
        "guard",
        "--harness",
        "crush",
        "--tool",
        tool,
        "--command",
        command,
        "--path",
        path,
        "--content",
        content,
    ]
    cwd = payload.get("cwd")
    if isinstance(cwd, str) and cwd:
        args.extend(["--cwd", cwd])

    result = subprocess.run(
        args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    try:
        verdict = json.loads(result.stdout)
    except ValueError:
        detail = result.stderr.strip() or "no guard output"
        return deny(f"shared guard failed closed: {detail}")

    decision = verdict.get("decision", "deny")
    reason = verdict.get("reason", "shared guard failed closed")
    if decision == "deny":
        return deny(reason)
    if decision == "warn" and reason:
        print(reason, file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_pi_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

{agent["prompt"].strip()}
"""


def render_omp_agent(agent: dict[str, Any]) -> str:
    return f"""---
name: {agent["id"]}
description: {json.dumps(agent["description"])[1:-1]}
---

{MANAGED_HEADER}

Before acting, read `{agent["shared"]}`. Use its `developer_instructions` as the complete specialist role and follow the shared harness instructions from `~/.agents/harness/instructions.md`.
"""


def render_omp_append_system() -> str:
    instructions = render_instructions()
    return f"""{instructions}

{COMPACTION_PRESERVATION}
# Git Commit Attribution

When creating any Git commit, append this trailer exactly once after a blank line:

Co-Authored-By: oh-my-pi <omp@can.ac>
"""


def render_opencode_config(
    commands: list[dict[str, Any]], agents: list[dict[str, Any]]
) -> str:
    config = {
        "$schema": "https://opencode.ai/config.json",
        "instructions": ["~/.agents/harness/instructions.md"],
        "model": "anthropic/claude-sonnet-4-20250514",
        "small_model": "anthropic/claude-haiku-3-5-20241022",
        "share": "manual",
        "autoupdate": "notify",
        "permission": {
            "edit": "ask",
            "bash": {
                "git status*": "allow",
                "git diff*": "allow",
                "git log*": "allow",
                "git show*": "allow",
                "rg *": "allow",
                "find *": "allow",
                "ls *": "allow",
                "just harness-check": "allow",
                "rm *": "ask",
                "sudo *": "deny",
            },
            "external_directory": "ask",
            "webfetch": "ask",
        },
        "command": {
            command["native"]: {
                "description": command["description"],
                "template": f"Execute the shared harness command at {command['shared']} with arguments: $ARGUMENTS",
            }
            for command in commands
        },
        "agent": {
            agent["id"]: {
                "description": agent["description"],
                "mode": "subagent",
                "prompt": f"Load and follow the shared specialist agent definition at {agent['shared']} before acting.",
                "permission": {
                    "edit": "ask",
                    "bash": "ask",
                    "webfetch": "ask",
                    "external_directory": "ask",
                },
            }
            for agent in agents
        },
    }
    return json.dumps(config, indent=2, sort_keys=True) + "\n"


def render_opencode_plugin() -> str:
    return """// Generated by scripts/agent-harnesses.py; do not edit directly.
// Copyright: Ben Chatelain. Apache 2.0.

import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import type { Plugin } from "@opencode-ai/plugin";

type GuardResult = { decision: "allow" | "warn" | "deny"; reason?: string };

function guard(args: string[]): GuardResult {
  const script = join(homedir(), "scripts", "agent-harnesses.py");
  try {
    const output = execFileSync("python3", [script, "guard", "--harness", "opencode", ...args], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output) as GuardResult;
  } catch (error: any) {
    const output = error?.stdout?.toString?.() || "";
    if (output) return JSON.parse(output) as GuardResult;
    return { decision: "deny", reason: "Shared guard failed closed" };
  }
}

export const HarnessPlugin: Plugin = async () => ({
  async "experimental.chat.system.transform"(_input, output) {
    output.system.push("Use shared harness instructions from ~/.agents/harness/instructions.md.");
  },

  async "experimental.session.compacting"(_input, output) {
    output.context.push("Preserve modified files, current branch, pending tasks, test results, and harness parity gaps.");
  },

  async "tool.execute.before"(input, output) {
    const args = output.args || {};
    let result: GuardResult = { decision: "allow" };

    if (input.tool === "bash") {
      result = guard(["--tool", "bash", "--command", String(args.command || "")]);
    } else if (input.tool === "write" || input.tool === "edit") {
      const path = String(args.file_path || args.path || "");
      const content = String(args.content || args.new_string || "");
      result = guard(["--tool", input.tool, "--path", path, "--content", content]);
    }

    if (result.decision === "deny") {
      throw new Error(result.reason || "Blocked by shared harness guard");
    }
  },
});

export default HarnessPlugin;
"""


def render_pi_settings() -> str:
    existing: dict[str, Any] = {}
    settings_path = PI_AGENT / "settings.json"
    if settings_path.exists():
        existing = json.loads(settings_path.read_text())

    merged = {
        **existing,
        "defaultProvider": existing.get("defaultProvider", "anthropic"),
        "defaultModel": existing.get("defaultModel", "claude-opus-4-8"),
        "defaultThinkingLevel": existing.get("defaultThinkingLevel", "medium"),
        "defaultProjectTrust": existing.get("defaultProjectTrust", "ask"),
        "enableSkillCommands": True,
        "skills": ["~/.agents/skills"],
        "prompts": ["~/.pi/agent/prompts"],
        "extensions": ["~/.pi/agent/extensions/harness.ts"],
        "compaction": {
            "enabled": True,
            "reserveTokens": 16384,
            "keepRecentTokens": 20000,
        },
        "retry": {
            "enabled": True,
            "maxRetries": 3,
            "baseDelayMs": 2000,
            "provider": {"maxRetries": 0, "maxRetryDelayMs": 60000},
        },
        "shellCommandPrefix": existing.get("shellCommandPrefix", ""),
        "sessionDir": existing.get("sessionDir", "~/.pi/agent/sessions"),
    }
    return json.dumps(merged, indent=2, sort_keys=True) + "\n"


def render_pi_extension() -> str:
    return """// Generated by scripts/agent-harnesses.py; do not edit directly.
// Copyright: Ben Chatelain. Apache 2.0.

import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

type GuardResult = { decision: "allow" | "warn" | "deny"; reason?: string };

function guard(args: string[]): GuardResult {
  const script = join(homedir(), "scripts", "agent-harnesses.py");
  try {
    const output = execFileSync("python3", [script, "guard", "--harness", "pi", ...args], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return JSON.parse(output) as GuardResult;
  } catch (error: any) {
    const output = error?.stdout?.toString?.() || "";
    if (output) return JSON.parse(output) as GuardResult;
    return { decision: "deny", reason: "Shared guard failed closed" };
  }
}

export default function (pi: ExtensionAPI) {
  pi.on("session_start", (_event, ctx) => {
    ctx.ui.setStatus("harness", "shared harness");
  });

  pi.on("tool_call", async (event) => {
    let result: GuardResult = { decision: "allow" };
    if (event.toolName === "bash") {
      result = guard(["--tool", "bash", "--command", String(event.input.command || "")]);
    } else if (event.toolName === "write" || event.toolName === "edit") {
      const path = String(event.input.file_path || event.input.path || "");
      const content = String(event.input.content || event.input.new_string || "");
      result = guard(["--tool", event.toolName, "--path", path, "--content", content]);
    }
    if (result.decision === "deny") return { block: true, reason: result.reason || "Blocked by shared harness guard" };
    return undefined;
  });

  pi.registerCommand("harness-agents", {
    description: "List shared specialist agents",
    handler: async (_args, ctx) => {
      ctx.ui.notify("Shared specialist agents are registered in ~/.pi/agent/agents.json", "info");
    },
  });

  pi.registerTool({
    name: "harness_agent_registry",
    label: "Harness Agents",
    description: "Return the shared specialist agent registry.",
    parameters: Type.Object({}),
    async execute() {
      return {
        content: [{ type: "text", text: "Read ~/.pi/agent/agents.json for shared specialist agent definitions." }],
        details: { path: "~/.pi/agent/agents.json" },
      };
    },
  });
}
"""


def slim_agents(agents: list[dict[str, Any]]) -> list[dict[str, str]]:
    return [
        {
            "id": agent["id"],
            "description": agent["description"],
            "shared": agent["shared"],
        }
        for agent in agents
    ]


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines()
    end_index = None
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end_index = index
            break
    if end_index is None:
        return {}, text

    data: dict[str, str] = {}
    for line in lines[1:end_index]:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip().strip('"').strip("'")
        data[key.strip()] = value
    return data, "\n".join(lines[end_index + 1 :])


def first_nonempty_line(text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip(" #")
        if stripped and stripped != "---" and ":" not in stripped:
            return stripped
    return ""


def command_version(command: list[str]) -> str:
    if not shutil.which(command[0]):
        return ""
    try:
        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            check=False,
            timeout=5,
        )
    except subprocess.TimeoutExpired:
        return ""
    if result.returncode != 0:
        return ""
    return result.stdout.strip().splitlines()[-1] if result.stdout.strip() else ""


def display_path(path: Path) -> str:
    try:
        rel = path.resolve().relative_to(HOME)
    except ValueError:
        return str(path)
    return "~/" + rel.as_posix()


def parse_guard_args(argv: list[str]) -> Any:
    """Hand-parse the `guard` args to skip argparse on the hot hook path.

    Mirrors the guard subparser exactly (`--command` maps to `shell_command`,
    same defaults, `--harness`/`--tool` required). Returns a namespace, or None
    to fall back to the full argparse dispatcher for anything it cannot parse
    confidently (unknown flag, dangling value, invalid harness, missing tool) so
    error handling stays identical to argparse.
    """
    from types import SimpleNamespace

    flag_map = {
        "--harness": "harness",
        "--tool": "tool",
        "--command": "shell_command",
        "--path": "path",
        "--content": "content",
        "--cwd": "cwd",
    }
    opts: dict[str, str | None] = {
        "harness": None,
        "tool": None,
        "shell_command": "",
        "path": "",
        "content": "",
        "cwd": str(ROOT),
    }
    index = 0
    while index < len(argv):
        key = flag_map.get(argv[index])
        if key is None or index + 1 >= len(argv):
            return None
        opts[key] = argv[index + 1]
        index += 2
    if opts["harness"] not in HARNESSES or not opts["tool"]:
        return None
    return SimpleNamespace(**opts)


if __name__ == "__main__":
    if _IS_GUARD:
        _guard_ns = parse_guard_args(sys.argv[2:])
        if _guard_ns is not None:
            raise SystemExit(command_guard(_guard_ns))
    raise SystemExit(main())
