#!/usr/bin/env python3
"""Find gitignored files that look like configuration worth tracking.

Allowlist-style .gitignore rules fail safe: anything new under a harness
config root is ignored by default and never shows up in `git status`. That
trades visibility for safety. This script restores the visibility half by
listing ignored-but-untracked files, classifying each as secret, state, or
config candidate, and reporting only the candidates.

It also flags the inverse hazard: tracked files whose name or contents look
like credentials.

Usage:
    scan-ignored-config.py [ROOT ...] [--repo DIR] [--json] [--include-state]
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from harness_paths import CONFIG_ROOTS

# A root is "allowlist-governed" when .gitignore denies all of its children
# with `<root>/*` and re-includes specific paths with `!<root>/...`. Those are
# exactly the roots where a new config file never reaches `git status`, so
# those are the roots this scan exists for. A denylist-governed root needs no
# scan (anything new there is already visible), and a `<root>/*` rule with no
# re-includes is a blanket exclusion nobody curates — a package cache, not
# configuration.
DENY_RULE = re.compile(r"([^!#\s].*?)/\*")
REINCLUDE_RULE = re.compile(r"!(.+)")

# Agent-harness config roots. Scanning defaults to the intersection of these
# and the allowlist-governed roots above: a crate cache or a checkout of
# source repos is allowlist-governed too, but it is not harness config and
# reviewing it teaches nothing. Pass explicit ROOT arguments to look wider.
# `.agents` is shared skill/harness infrastructure, not one harness's config
# root, so it is unioned in here rather than living in `CONFIG_ROOTS`.
HARNESS_ROOTS = frozenset({".agents"} | {r for rs in CONFIG_ROOTS.values() for r in rs})

# Files that mark their directory as a third-party package root. The whole
# subtree, manifest included, is installed rather than hand-authored.
VENDOR_MARKERS = (
    ".claude-plugin",
    ".git",
    "Cargo.toml",
    "gemini-extension.json",
    "go.mod",
    "installed_version.json",
    "package.json",
    "plugin.json",
    "pyproject.toml",
)

# Native harness skill directories are generated from `.agents/skills/<name>`.
# One with no shared counterpart was installed by the harness itself or by a
# marketplace, so it reinstalls on a new machine and tracking it forks upstream.
NATIVE_SKILL_ROOTS = (
    ".claude/skills",
    ".codex/skills",
    ".config/opencode/skills",
    ".gemini/antigravity/skills",
    ".gemini/skills",
)

# Never propose tracking these. Credential material or machine identity.
SECRET_NAMES = frozenset(
    {
        ".credentials.json",
        ".env",
        "auth-broker.token",
        "auth-gateway.token",
        "auth.json",
        "credentials.json",
        "install-id",
        "secret-placeholder.key",
        "secrets.yaml",
        "secrets.yml",
        "trust.json",
    }
)
SECRET_SUFFIXES = (".enc", ".key", ".pem", ".p12", ".pfx", ".token")
SECRET_WORDS = re.compile(
    r"credential|passwd|password|secret|(^|[^a-z])auth([^a-z]|$)|token|oauth|cookie",
    re.IGNORECASE,
)

# Runtime state: regenerated by the tool, never worth a diff.
STATE_DIRS = frozenset(
    {
        ".remote-plugin-install-staging",
        ".system",
        ".tmp",
        "__pycache__",
        "agent-tools",
        "agent-transcripts",
        "ai-tracking",
        "ambient-suggestions",
        "artifacts",
        "attachments",
        "blobs",
        "build",
        "builtin",
        "bundled",
        "cache",
        "caches",
        "canvases",
        "chrome-native-hosts-v2",
        "computer-use",
        "cross-instance-locks",
        "daemon",
        "dist",
        "docs",
        "extensions",
        "handoffs",
        "history",
        "jobs",
        "log",
        "logs",
        "managed-skills",
        "marketplaces",
        "mcps",
        "natives",
        "node_modules",
        "npm",
        "plans",
        "process_manager",
        "python-env",
        "registry",
        "run",
        "security",
        "sessions",
        "shell_snapshots",
        "skills-cursor",
        "teams",
        "temp",
        "terminal-sessions",
        "terminals",
        "tmp",
        "venv",
        "worktrees",
    }
)
STATE_SUFFIXES = (
    ".bak",
    ".db",
    ".db-shm",
    ".db-wal",
    ".gif",
    ".gz",
    ".icns",
    ".jpg",
    ".jsonl",
    ".lock",
    ".log",
    ".node",
    ".pid",
    ".png",
    ".sock",
    ".sqlite",
    ".sqlite3",
    ".swp",
    ".tar",
    ".tmp",
    ".webm",
    ".zip",
)
STATE_NAMES = frozenset(
    {
        ".DS_Store",
        ".crates.toml",
        ".crates2.json",
        "argv.json",
        "chrome-native-hosts-v2.json",
        "external_agent_session_imports.json",
        "gpu_cache.json",
        "last-changelog-version",
        "version.json",
    }
)

# Directory or file names that mark generated caches, bundled downloads, and
# status snapshots.
STATE_SHAPES = re.compile(
    r"(^|[-_.])cache([-_.]|$)"
    r"|marketplace"
    r"|\.app$"
    r"|[-_.](state|stats|status|result|check|snapshot|lock)\.[a-z]+$"
    r"|^[0-9a-f]{32,64}\.[a-z]+$",
    re.IGNORECASE,
)

# Extensions that plausibly hold hand-authored configuration.
CONFIG_SUFFIXES = frozenset(
    {
        ".bash",
        ".cfg",
        ".conf",
        ".fish",
        ".ini",
        ".js",
        ".json",
        ".jsonc",
        ".lua",
        ".md",
        ".mdc",
        ".mjs",
        ".py",
        ".sh",
        ".toml",
        ".ts",
        ".yaml",
        ".yml",
        ".zsh",
    }
)

# Content patterns that disqualify an otherwise config-shaped file.
SECRET_CONTENT = (
    ("openai-style key", re.compile(r"\bsk-[A-Za-z0-9_-]{16,}")),
    ("github token", re.compile(r"\b(gh[pousr]_[A-Za-z0-9]{16,}|github_pat_[\w]{20,})")),
    ("aws access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}")),
    ("private key block", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    ("jwt", re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.")),
    (
        "assigned credential",
        re.compile(
            # allow an optional closing quote after the key so JSON
            # ("apiKey": "…") matches as well as shell/yaml (key=value) forms
            r"(?i)\b(api[_-]?key|secret|password|passwd|access[_-]?token|bearer)"
            r"\b[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-./+]{16,}"
        ),
    ),
    # Not a credential, but the same never-track class: a trust grant records a
    # directory vetted on one machine. Copying it auto-approves that path on a
    # fresh host. Caught by name as trust.json; this catches it as a key.
    (
        "trust grant",
        re.compile(
            r"(?i)\"(trusted[_-]?(workspaces|folders|paths|dirs|roots)"
            r"|workspace[_-]?trust)\"\s*:\s*\[\s*[^\]\s]"
        ),
    ),
)

# Tracked files whose credential-shaped names are the detector, not the
# credential — verified false positives.
TRACKED_ALLOWLIST = frozenset(
    {
        ".codex/hooks/scripts/user-prompt-secrets.sh",
    }
)

CONTENT_SCAN_LIMIT = 1 << 20  # 1 MiB


def classify(relpath):
    """Return 'secret', 'state', 'config', or 'other' for a repo-relative path."""
    path = Path(relpath)
    name = path.name
    lower = name.lower()

    if name in SECRET_NAMES or lower.startswith(".env."):
        return "secret"
    if lower.endswith(SECRET_SUFFIXES) or SECRET_WORDS.search(lower):
        return "secret"

    if STATE_DIRS.intersection(path.parts[:-1]):
        return "state"
    if name in STATE_NAMES or lower.endswith(STATE_SUFFIXES):
        return "state"
    if any(STATE_SHAPES.search(part) for part in path.parts):
        return "state"

    if path.suffix.lower() in CONFIG_SUFFIXES:
        return "config"
    return "other"


def sniff_secrets(path):
    """Return names of secret patterns found in a file, or [] if clean."""
    try:
        blob = path.read_bytes()[:CONTENT_SCAN_LIMIT]
    except OSError:
        return []
    if b"\0" in blob[:8192]:
        return []
    text = blob.decode("utf-8", errors="replace")
    return [label for label, pattern in SECRET_CONTENT if pattern.search(text)]


def is_package_root(repo, reldir, memo):
    """True if reldir holds a vendor marker, memoized per directory."""
    cached = memo.get(reldir)
    if cached is None:
        cached = any((repo / reldir / marker).exists() for marker in VENDOR_MARKERS)
        memo[reldir] = cached
    return cached


def is_vendored(repo, relpath, memo, stop_at=frozenset()):
    """True if relpath sits inside a third-party package or nested clone.

    A vendor marker sitting at a scan root itself (e.g. the package.json a
    harness npm-installs plugins into its own config dir with) does not vendor
    hand-authored files living directly at that root — only nested packages do.
    """
    parent = Path(relpath).parent
    while parent != Path(".") and str(parent) not in stop_at:
        if is_package_root(repo, parent, memo):
            return True
        parent = parent.parent
    return False


def is_unshared_skill(repo, relpath):
    """True if relpath is a native skill with no `.agents/skills` counterpart."""
    for root in NATIVE_SKILL_ROOTS:
        prefix = f"{root}/"
        if relpath.startswith(prefix):
            name = relpath[len(prefix) :].split("/", 1)[0]
            return not (repo / ".agents" / "skills" / name).is_dir()
    return False


def git_lines(repo, args):
    """Run a git command in repo and return its NUL-separated output as a list."""
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        check=True,
    )
    return [line for line in result.stdout.split("\0") if line]


def scan_ignored(repo, roots):
    """Classify every ignored, untracked file under roots."""
    found = []
    vendored = {}
    for entry in git_lines(
        repo, ["ls-files", "-z", "--others", "--ignored", "--exclude-standard", "--", *roots]
    ):
        kind = classify(entry)
        if kind not in ("config", "state"):
            continue
        if kind == "config" and (
            is_vendored(repo, entry, vendored, roots) or is_unshared_skill(repo, entry)
        ):
            kind = "state"
        record = {"path": entry, "kind": kind, "warnings": []}
        if kind == "config":
            record["warnings"] = sniff_secrets(repo / entry)
            if record["warnings"]:
                record["kind"] = "review"
        found.append(record)
    return found


def scan_tracked(repo, roots):
    """Flag tracked files that are named or shaped like credentials."""
    flagged = []
    for entry in git_lines(repo, ["ls-files", "-z", "--", *roots]):
        if entry in TRACKED_ALLOWLIST:
            continue
        warnings = []
        if classify(entry) == "secret":
            warnings.append("credential-shaped name")
        warnings.extend(sniff_secrets(repo / entry))
        if warnings:
            flagged.append({"path": entry, "warnings": warnings})
    return flagged


def render(candidates, review, state, flagged, include_state):
    """Print a markdown report. Returns nothing."""
    print("## Ignored configuration coverage\n")

    if candidates:
        print("### Candidates worth tracking\n")
        print("| Path | Size |")
        print("|---|---|")
        for item in candidates:
            print(f"| `{item['path']}` | {item['size']} B |")
        print()
    else:
        print("No untracked configuration candidates. Coverage is complete.\n")

    if review:
        print("### Config-shaped but contains credential material — do not track as-is\n")
        print("| Path | Detected |")
        print("|---|---|")
        for item in review:
            print(f"| `{item['path']}` | {', '.join(item['warnings'])} |")
        print()

    if flagged:
        print("### Tracked files that look like credentials — audit these\n")
        print("| Path | Detected |")
        print("|---|---|")
        for item in flagged:
            print(f"| `{item['path']}` | {', '.join(item['warnings'])} |")
        print()

    if include_state and state:
        print(f"### Ignored runtime state ({len(state)} files, correctly excluded)\n")
        for item in state[:50]:
            print(f"- `{item['path']}`")
        if len(state) > 50:
            print(f"- ... and {len(state) - 50} more")
        print()


def allowlist_roots(repo):
    """Derive curated allowlist-governed roots from the repo .gitignore."""
    ignore_file = repo / ".gitignore"
    if not ignore_file.is_file():
        return []
    denied = set()
    curated = set()
    for line in ignore_file.read_text().splitlines():
        line = line.strip()
        deny = DENY_RULE.fullmatch(line)
        if deny:
            denied.add(deny.group(1))
            continue
        keep = REINCLUDE_RULE.fullmatch(line)
        if keep:
            curated.add(keep.group(1))
    # Curation can be declared at any depth: `!.omp/agent/config.yml` curates
    # `.omp`. Match a denied root against every re-included ancestor path.
    roots = {
        root
        for root in denied
        if (repo / root).is_dir()
        and any(kept == root or kept.startswith(root + "/") for kept in curated)
    }
    # Keep only outermost roots; nested `<root>/sub/*` rules add no coverage.
    outermost = {r for r in roots if not any(r.startswith(o + "/") for o in roots - {r})}
    return sorted(outermost & HARNESS_ROOTS)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("roots", nargs="*", help="paths to scan (default: allowlisted roots)")
    parser.add_argument("--repo", default=str(Path.home()), help="repository root")
    parser.add_argument("--json", action="store_true", help="emit JSON instead of markdown")
    parser.add_argument(
        "--include-state", action="store_true", help="also list ignored runtime state"
    )
    args = parser.parse_args()

    repo = Path(args.repo).expanduser().resolve()
    roots = args.roots or allowlist_roots(repo)
    if not roots:
        print("No config roots found to scan.", file=sys.stderr)
        return 0

    ignored = scan_ignored(repo, roots)
    candidates = []
    for item in (i for i in ignored if i["kind"] == "config"):
        item["size"] = (repo / item["path"]).stat().st_size
        candidates.append(item)
    candidates.sort(key=lambda i: i["path"])
    review = sorted((i for i in ignored if i["kind"] == "review"), key=lambda i: i["path"])
    state = sorted((i for i in ignored if i["kind"] == "state"), key=lambda i: i["path"])
    flagged = scan_tracked(repo, roots)

    if args.json:
        json.dump(
            {
                "roots": roots,
                "candidates": candidates,
                "review": review,
                "state": state if args.include_state else [],
                "tracked_flagged": flagged,
            },
            sys.stdout,
            indent=2,
        )
        print()
    else:
        render(candidates, review, state, flagged, args.include_state)
    return 0


if __name__ == "__main__":
    sys.exit(main())
