#!/usr/bin/env bash
# Claude model catalog: lockfile generation and drift/retirement checking.
#
# Current Claude model IDs (claude-opus-5, claude-sonnet-5, ...) carry no date
# suffix, so there is no version to pin in agent frontmatter. Instead we record
# what the live API reports into a tracked lockfile, so git history documents
# which model generation was in use and when it changed.
#
# Retirement data is NOT in the Models API -- it lives only in the deprecations
# doc, so we cross-reference both:
#   * absent from /v1/models          -> RETIRED (hard failure)
#   * listed Deprecated in the doc    -> warning, with days remaining
#
# Requires: curl, jq
#
#   claude-models.sh lock    # refresh .claude/models.lock
#   claude-models.sh check   # compare live API against the lockfile

set -euo pipefail

readonly API="https://api.anthropic.com/v1/models"
readonly DEPRECATIONS_URL="https://platform.claude.com/docs/en/about-claude/model-deprecations.md"
readonly LOCKFILE="${CLAUDE_MODELS_LOCK:-$HOME/.claude/models.lock}"
readonly CREDS="$HOME/.claude/.credentials.json"

die() {
  printf 'claude-models: %s\n' "$*" >&2
  exit 1
}

# Resolve credentials: explicit API key wins, else Claude Code's OAuth token.
# Sets AUTH_HEADER and BETA_HEADER; never echoes the secret.
resolve_auth() {
  if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -f "$HOME/.env" ]; then
    set -a
    # shellcheck disable=SC1091
    . "$HOME/.env"
    set +a
  fi

  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    AUTH_HEADER="x-api-key: $ANTHROPIC_API_KEY"
    BETA_HEADER="anthropic-version: 2023-06-01"
    return
  fi

  [ -f "$CREDS" ] || die "no credentials — set ANTHROPIC_API_KEY in ~/.env, or log in to Claude Code"

  local token expires now
  token=$(jq -r '.claudeAiOauth.accessToken // empty' "$CREDS" 2>/dev/null || true)
  [ -n "$token" ] || die "could not read an OAuth token from $CREDS"

  expires=$(jq -r '.claudeAiOauth.expiresAt // 0' "$CREDS")
  now=$(($(date +%s) * 1000))
  if [ "$expires" -le "$now" ]; then
    die "Claude Code OAuth token expired — reopen Claude Code to refresh, or set ANTHROPIC_API_KEY"
  fi

  AUTH_HEADER="Authorization: Bearer $token"
  BETA_HEADER="anthropic-beta: oauth-2025-04-20"
}

# Fetch every model, following the after_id cursor. Emits the merged .data array.
fetch_models() {
  local page after='' all='[]' body status
  while :; do
    page=$(curl -sS --max-time 30 "$API?limit=100${after:+&after_id=$after}" \
      -H "$AUTH_HEADER" \
      -H "anthropic-version: 2023-06-01" \
      -H "$BETA_HEADER" \
      -w $'\n%{http_code}') || die "request to /v1/models failed (network or timeout)"

    status=${page##*$'\n'}
    body=${page%$'\n'*}

    case $status in
    2*) ;;
    401 | 403) die "HTTP $status — credentials rejected by /v1/models" ;;
    429) die "HTTP 429 — rate limited; retry shortly" ;;
    *) die "HTTP $status — $(printf '%s' "$body" | jq -r '.error.message // .' 2>/dev/null | head -c 200)" ;;
    esac

    all=$(printf '%s\n%s' "$all" "$body" | jq -s '.[0] + .[1].data')
    [ "$(printf '%s' "$body" | jq -r '.has_more')" = true ] || break
    after=$(printf '%s' "$body" | jq -r '.last_id')
  done
  printf '%s' "$all"
}

# Parse the deprecations doc's status table into TSV: id<TAB>state<TAB>retire_date
fetch_deprecations() {
  curl -sS --max-time 30 "$DEPRECATIONS_URL" 2>/dev/null |
    awk -F'|' '
      /^\| *claude-[a-z0-9.-]+ *\|/ {
        gsub(/^[ \t]+|[ \t]+$/, "", $2)
        gsub(/^[ \t]+|[ \t]+$/, "", $3)
        gsub(/^[ \t]+|[ \t]+$/, "", $5)
        print $2 "\t" $3 "\t" $5
      }' || true
}

render_lock() {
  local models=$1 deprecations=$2 generated=$3 out=$4
  {
    printf '# Claude model catalog — generated by scripts/claude-models.sh\n'
    printf '# Source: GET /v1/models + %s\n' "$DEPRECATIONS_URL"
    printf '# Regenerate: just update-models\n'
    printf '# generated: %s\n' "$generated"
    printf '#\n'
    printf '# %-28s %-10s %9s %8s  %s\n' id state ctx max_out retires
    printf '%s' "$models" | jq -r '.[] | [.id, (.max_input_tokens|tostring), (.max_tokens|tostring)] | @tsv' |
      sort |
      while IFS=$'\t' read -r id ctx maxout; do
        local state retires line
        line=$(printf '%s' "$deprecations" | awk -F'\t' -v m="$id" '$1 == m {print; exit}')
        state=$(printf '%s' "$line" | cut -f2)
        retires=$(printf '%s' "$line" | cut -f3)
        [ -n "$state" ] || state="Active"
        [ -n "$retires" ] || retires="unknown"
        printf '  %-28s %-10s %9s %8s  %s\n' "$id" "$state" "$ctx" "$maxout" "$retires"
      done
  } >"$out"
}

cmd_lock() {
  resolve_auth
  local models deprecations generated
  models=$(fetch_models)
  deprecations=$(fetch_deprecations)
  generated=$(date -u +%Y-%m-%d)

  mkdir -p "$(dirname "$LOCKFILE")"
  render_lock "$models" "$deprecations" "$generated" "$LOCKFILE"

  printf 'Wrote %s (%s models)\n' "$LOCKFILE" "$(printf '%s' "$models" | jq 'length')"
}

# Model IDs assigned in tracked config — only structured `model:` / "model":
# fields, never prose, so a model named in a sentence is not a false positive.
# Bare tier keywords (sonnet, opus, haiku, inherit) are resolved by the harness,
# not the API, so they are skipped by requiring the claude-* prefix.
tracked_model_ids() {
  # No \b — git grep's ERE does not support it and silently matches nothing.
  # --untracked so a newly added agent is checked before it is committed;
  # it still honours .gitignore, so vendored plugin fixtures stay excluded.
  git -C "$HOME" grep --untracked -hoE '"?model"?: *"?(claude-[a-z]+-[0-9][a-z0-9-]*)' -- \
    '.claude/agents' '.claude/skills' '.claude/settings.json' '.codex/agents' 2>/dev/null |
    grep -oE 'claude-[a-z]+-[0-9][a-z0-9-]*' |
    sed 's/-*$//' |
    sort -u || true
}

# Resolve one model ID against the API. Aliases (claude-haiku-4-5) resolve even
# though the list endpoint reports only their dated form, so this is the
# authoritative liveness check — 200 = usable, 404 = retired or nonexistent.
model_is_live() {
  local status
  status=$(curl -sS --max-time 20 -o /dev/null -w '%{http_code}' \
    "$API/$1" \
    -H "$AUTH_HEADER" \
    -H "anthropic-version: 2023-06-01" \
    -H "$BETA_HEADER") || return 2
  [ "$status" = 200 ]
}

cmd_check() {
  resolve_auth
  local models deprecations live today rc=0
  models=$(fetch_models)
  deprecations=$(fetch_deprecations)
  live=$(printf '%s' "$models" | jq -r '.[].id' | sort)
  today=$(date -u +%s)

  # 1. Retirement / deprecation status of everything currently live.
  local id state retires retire_epoch days
  while IFS= read -r id; do
    [ -n "$id" ] || continue
    state=$(printf '%s' "$deprecations" | awk -F'\t' -v m="$id" '$1 == m {print $2; exit}')
    retires=$(printf '%s' "$deprecations" | awk -F'\t' -v m="$id" '$1 == m {print $3; exit}')
    case $state in
    Deprecated)
      retire_epoch=$(date -j -f '%B %d, %Y' "$retires" +%s 2>/dev/null || echo 0)
      if [ "$retire_epoch" -gt 0 ]; then
        days=$(((retire_epoch - today) / 86400))
        printf '  ! %-28s DEPRECATED — retires %s (%s days)\n' "$id" "$retires" "$days"
      else
        printf '  ! %-28s DEPRECATED — retires %s\n' "$id" "$retires"
      fi
      ;;
    esac
  done <<<"$live"

  # 2. Model IDs referenced by tracked config but absent from the API = retired.
  local referenced
  referenced=$(tracked_model_ids)
  while IFS= read -r id; do
    [ -n "$id" ] || continue
    if ! model_is_live "$id"; then
      printf '  x %-28s RETIRED or unavailable — referenced in tracked config\n' "$id"
      rc=1
    fi
  done <<<"$referenced"

  # 3. Drift against the lockfile.
  if [ ! -f "$LOCKFILE" ]; then
    printf '  ? no lockfile at %s — run: just update-models\n' "$LOCKFILE"
    return "$rc"
  fi
  local tmp
  tmp=$(mktemp)
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN
  render_lock "$models" "$deprecations" "$(awk '/^# generated:/{print $3}' "$LOCKFILE")" "$tmp"

  if diff -q <(grep -v '^# generated:' "$LOCKFILE") <(grep -v '^# generated:' "$tmp") >/dev/null; then
    printf '  ok %s models live, lockfile in sync\n' "$(printf '%s' "$live" | grep -c .)"
  else
    printf '  ~ lockfile drift — run: just update-models\n'
    # diff exits 1 when files differ; that is the expected path here, so don't
    # let `set -e` + pipefail abort before the return below.
    diff <(grep -v '^# generated:' "$LOCKFILE") <(grep -v '^# generated:' "$tmp") |
      grep -E '^[<>]' | sed 's/^/    /' || true
  fi

  # Only a retired model still referenced by tracked config is a hard failure;
  # deprecations and lockfile drift are informational so `just outdated` keeps going.
  return "$rc"
}

main() {
  case "${1:-}" in
  lock) cmd_lock ;;
  check) cmd_check ;;
  *) die "usage: claude-models.sh {lock|check}" ;;
  esac
}

main "$@"
