#!/usr/bin/env bash
#
# Renders each OMP profile's config.yml from the main config plus its
# overrides.yml.
#
# Usage: generate-omp-profiles.sh
#
# Copyright: Ben Chatelain. MIT
#
# OMP has no profile inheritance. This deep-merges with OMP's own rules: maps
# merge, scalars and arrays replace. Main's modelRoles are emptied first so a
# profile never inherits roles naming providers it lacks.

set -euo pipefail

command -v yq > /dev/null || {
    echo "error: yq is required" >&2
    exit 1
}

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
main="$root/.omp/agent/config.yml"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

render() {
    cat << 'EOF'
# Generated by `just generate-omp-profiles` from .omp/agent/config.yml and the
# overrides.yml beside this file. Edit overrides.yml, then re-render: OMP writes
# /settings changes here, and the next render discards them.
EOF
    yq eval-all '(select(fileIndex == 0) | .modelRoles = {}) * select(fileIndex == 1) | ... comments = ""' "$main" "$1"
}

for overrides in "$root"/.omp/profiles/*/agent/overrides.yml; do
    [[ -f "$overrides" ]] || continue
    out="$(dirname "$overrides")/config.yml"
    render "$overrides" > "$tmp"
    # cp, not mv: keeps the existing file's mode and inode.
    cp "$tmp" "$out"
    echo "Rendered ${out#"$root"/}"
done
