GOOSE_PROVIDER: openai
OPENAI_BASE_PATH: v1/chat/completions
extensions:
  Puppeteer:
    args:
    - -y
    - '@modelcontextprotocol/server-puppeteer'
    cmd: npx
    enabled: true
    envs: {}
    name: Puppeteer
    type: stdio
  computercontroller:
    enabled: true
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  jetbrains:
    enabled: true
    name: jetbrains
    type: builtin
GOOSE_MODEL: gpt-4o
OPENAI_HOST: https://api.openai.com
